import type { DashboardPerformance } from "@/lib/api/dashboard-performance";
import type { TeamPerformanceRepRow } from "@/lib/types";

type Locale = "ar" | "en";

export interface TeamExecutiveDeckInput {
  companyName: string;
  scopeLabel: string;
  currentPeriod: { from: string; to: string };
  referencePeriod?: { from: string; to: string };
  dashboard: DashboardPerformance;
  reps: TeamPerformanceRepRow[];
  compareMode: boolean;
  locale: Locale;
}

type ExecutiveDiagnosis = {
  summary: string;
  evidence: string[];
  interpretation: string;
  unknown: string;
  confidence: string;
  decision: string;
  actions: string[];
};

const colors = { navy: "0B1220", surface: "162235", line: "314158", ink: "E8EEF8", muted: "94A3B8", blue: "3B82F6", green: "22C55E", amber: "F59E0B", red: "EF4444", pale: "D7E2F2" };

const copy = (locale: Locale) => locale === "ar" ? {
  title: "مراجعة أداء الفريق", snapshot: "اللقطة التنفيذية", story: "قصة الأداء", growth: "النمو والاتجاه", targets: "الأداء مقابل الهدف", comparison: "مقارنة الفريق", diagnosis: "التشخيص التنفيذي", decision: "القرار وخطة التنفيذ", fact: "الحقيقة", entity: "الكيان", salesDelta: "تغير المبيعات", current: "الحالي", reference: "المرجعي", actual: "المحقق", targetToDate: "الهدف حتى اليوم", gap: "الفجوة", achievement: "نسبة الإنجاز", required: "المطلوب يوميًا", forecast: "توقع نهاية الشهر", evidence: "الأدلة", interpretation: "التفسير", unknown: "ما لا يمكن إثباته", confidence: "درجة الثقة", decisionLabel: "القرار التنفيذي", actions: "إجراءات عالية التأثير", top: "الأفضل أداءً", risk: "أكبر مخاطرة", generated: "تاريخ الإنشاء", period: "الفترة الحالية", referencePeriod: "الفترة المرجعية", powered: "Murshidak | Field Sales OS", noData: "لا توجد بيانات كافية لإضافة استنتاج موثوق", sales: "المبيعات", collections: "التحصيل", customers: "العملاء المشترون", invoices: "الفواتير", skus: "الأصناف المباعة", returns: "المرتجعات", target: "الهدف", status: "الحالة",
} : {
  title: "Team Performance Review", snapshot: "Executive Snapshot", story: "Performance Story", growth: "Growth & Trend", targets: "Target Performance", comparison: "Team Comparison", diagnosis: "Executive Diagnosis", decision: "Decision & Action Plan", fact: "Fact", entity: "Entity", salesDelta: "Sales delta", current: "Current", reference: "Reference", actual: "Actual", targetToDate: "Target to date", gap: "Gap", achievement: "Achievement", required: "Required daily", forecast: "Month-end forecast", evidence: "Evidence", interpretation: "Interpretation", unknown: "What cannot be proven", confidence: "Confidence", decisionLabel: "Management decision", actions: "High-impact actions", top: "Top performer", risk: "Biggest risk", generated: "Generated", period: "Current period", referencePeriod: "Reference period", powered: "Murshidak | Field Sales OS", noData: "Not enough evidence for a reliable conclusion", sales: "Sales", collections: "Collections", customers: "Buying customers", invoices: "Invoices", skus: "Sold SKUs", returns: "Returns", target: "Target", status: "Status",
};

const format = (value: number | null, currency = false, rtl = false) => value === null || !Number.isFinite(value) ? "—" : `${Math.round(value).toLocaleString("en-US")}${currency ? (rtl ? " ر.س." : " SAR") : ""}`;
const pct = (value: number | null) => value === null || !Number.isFinite(value) ? "—" : `${value >= 0 ? "+" : ""}${value.toFixed(1)}%`;
const signed = (value: number | null, currency = false, rtl = false) => value === null ? "—" : `${value >= 0 ? "+" : ""}${format(value, currency, rtl)}`;
const tone = (value: number | null, lowerIsBetter = false) => value === null ? colors.muted : (lowerIsBetter ? value <= 0 : value >= 0) ? colors.green : value > -5 ? colors.amber : colors.red;

type DiagnosisFocus = "sales" | "collections" | "invoices" | "customers" | "skus" | "returns";

function buildFocusedDiagnosis(dashboard: DashboardPerformance, locale: Locale, focus: DiagnosisFocus): ExecutiveDiagnosis {
  const m = dashboard.metrics; const ar = locale === "ar";
  const labels: Record<DiagnosisFocus, string> = { sales: ar ? "المبيعات" : "Sales", collections: ar ? "التحصيل" : "Collections", invoices: ar ? "الفواتير" : "Invoices", customers: ar ? "العملاء المشترون" : "Buying customers", skus: ar ? "الأصناف المباعة" : "Sold SKUs", returns: ar ? "المرتجعات" : "Returns" };
  const key = focus === "collections" ? "collections" : focus;
  const value = m[key].growthPct;
  const related = focus === "sales" ? [m.customers.growthPct, m.invoices.growthPct] : focus === "collections" ? [m.sales.growthPct] : focus === "invoices" ? [m.sales.growthPct, m.customers.growthPct] : focus === "customers" ? [m.sales.growthPct, m.invoices.growthPct] : focus === "skus" ? [m.sales.growthPct] : [m.sales.growthPct, m.skus.growthPct];
  const evidence = [`${labels[focus]} ${pct(value)}`, ...related.map((x, i) => x === null ? null : `${[ar ? "المبيعات" : "Sales", ar ? "العملاء" : "Customers", ar ? "الفواتير" : "Invoices"][i]} ${pct(x)}`).filter((x): x is string => Boolean(x))];
  if (value === null || related.filter((x) => x !== null).length === 0) return { summary: ar ? `لا توجد أدلة مترابطة كافية لتشخيص ${labels[focus]}.` : `There is not enough connected evidence to diagnose ${labels[focus]}.`, evidence: evidence.filter((x) => !x.endsWith("—")), interpretation: ar ? "المؤشر وحده لا يثبت سببًا تشغيليًا." : "One metric alone does not establish an operating cause.", unknown: ar ? "لا يمكن استنتاج سبب ميداني أو سلوك عميل من هذه البيانات." : "A field cause or customer behavior cannot be inferred from these data.", confidence: ar ? "منخفضة" : "Low", decision: ar ? "استكمل بيانات المقارنة قبل اتخاذ قرار." : "Complete comparison data before deciding.", actions: ar ? ["راجع اكتمال الفترة المرجعية.", "استكمل بيانات الزيارة أو SKU عند الحاجة."] : ["Check reference-period completeness.", "Add visit or SKU detail where needed."] };
  if (focus === "returns") return { summary: value > 0 ? (ar ? "المرتجعات ترتفع وتستحق مراجعة نمطها." : "Returns are rising and require pattern review.") : (ar ? "المرتجعات تتحسن مقارنة بالفترة المرجعية." : "Returns are improving versus the reference period."), evidence, interpretation: value > 0 ? (ar ? "قد يشير الارتفاع إلى عدم ملاءمة كمية أو تشكيلة؛ لا يثبت جودة أو مخزون." : "The increase may indicate quantity or assortment mismatch; it does not prove quality or stock.") : (ar ? "التحسن إشارة إيجابية، لكن سببه التشغيلي غير مثبت." : "The improvement is positive, but its operating cause is unproven."), unknown: ar ? "لا يمكن إثبات تكرار SKU أو التحميل الزائد دون تفاصيل SKU والكمية." : "Repeat-SKU pattern and overloading require SKU and quantity detail.", confidence: ar ? "متوسطة" : "Medium", decision: value > 0 ? (ar ? "راجع المرتجعات قبل زيادة التحميل." : "Review returns before increasing loading.") : (ar ? "حافظ على الضبط الحالي للتحميل." : "Maintain current loading discipline."), actions: ar ? ["حدد الأصناف أو العملاء المتكررين.", "قارن التوريد بالتصريف.", "عدّل الكمية تدريجيًا."] : ["Identify recurrent SKUs or customers.", "Compare supplied quantity with sell-through.", "Adjust quantity gradually."] };
  const direction = value >= 0 ? (ar ? "يتحسن" : "is improving") : (ar ? "يتراجع" : "is declining");
  const plans: Record<Exclude<DiagnosisFocus, "returns">, { interpretation: string; unknown: string; decision: string; actions: string[] }> = {
    sales: { interpretation: ar ? "اقرأ المبيعات مع العملاء والفواتير لتحديد إن كان الضغط تغطية أم عمق طلبية." : "Read sales with customers and invoices to distinguish coverage from order depth.", unknown: ar ? "لا يمكن إثبات السعر أو المخزون أو سبب العميل دون تفاصيل أدق." : "Price, stock, and customer-level cause are not proven without detail.", decision: ar ? "وجّه المراجعة إلى المحرك الأقوى في المؤشرات المرتبطة." : "Direct review to the strongest linked driver.", actions: ar ? ["راجع العملاء والفواتير معًا.", "افحص الرف قبل اقتراح طلبية محددة.", "راقب قيمة الطلبية."] : ["Review customers and invoices together.", "Check the shelf before a specific proposal.", "Monitor order value."] },
    collections: { interpretation: ar ? "التحصيل مؤشر ائتماني؛ قارنه بالمبيعات دون افتراض أن العملاء أنفسهم هم السبب." : "Collections are a credit signal; compare them with sales without assuming the same customers cause both.", unknown: ar ? "لا يمكن إثبات هوية العملاء المتعثرين من بيانات الإجماليات." : "Aggregate data do not identify the delinquent customers.", decision: ar ? "أعطِ التحصيل أولوية قبل توسيع الائتمان." : "Prioritize collections before expanding credit.", actions: ar ? ["راجع المتأخرات أولًا.", "حدد موعد تحصيل واضحًا.", "أعد تقييم إعادة الطلب بعد التحصيل."] : ["Review overdue accounts first.", "Set a clear collection date.", "Reassess reorder after collection."] },
    invoices: { interpretation: ar ? "الفواتير تعكس تكرار الطلب، لا عدد الزيارات؛ اربطها بالمبيعات والعملاء." : "Invoices indicate order frequency, not visits; read them with sales and customers.", unknown: ar ? "لا يمكن استنتاج عدد الزيارات من الفواتير." : "Visit count cannot be inferred from invoices.", decision: ar ? "راجع تكرار الطلب قبل زيادة عدد الزيارات." : "Review order frequency before increasing visits.", actions: ar ? ["راجع العملاء ذوي الطلبات المتوقفة.", "حدد طلبية تالية واضحة.", "راقب معدل الفواتير."] : ["Review customers with stopped orders.", "Set a clear next order.", "Monitor invoice rate."] },
    customers: { interpretation: ar ? "العملاء المشترون يوضحون اتساع القاعدة المنتجة، لا جودة الزيارة وحدها." : "Buying customers show productive-base breadth, not visit quality alone.", unknown: ar ? "لا يمكن نسبة التغير إلى الزيارات دون بيانات زيارات فعلية." : "The change cannot be attributed to visits without actual visit data.", decision: ar ? "استعد العملاء المتوقفين قبل توسيع النطاق." : "Recover stopped customers before expanding scope.", actions: ar ? ["حدد العملاء المتوقفين.", "افحص الرف أولًا.", "تابع عودة العملاء في الفترة التالية."] : ["Identify stopped customers.", "Inspect the shelf first.", "Track reactivation next period."] },
    skus: { interpretation: ar ? "الأصناف المباعة تقيس اتساع التشكيلة؛ التغير قد يعكس توزيعًا أو عرضًا أو توافرًا." : "Sold SKUs measure assortment breadth; movement may reflect distribution, offer, or availability.", unknown: ar ? "لا يمكن إثبات نفاد مخزون أو سبب SKU دون بيانات صنف فعلية." : "Stock-out or a specific SKU cause is not proven without SKU data.", decision: ar ? "راجع التشكيلة قبل رفع الضغط البيعي." : "Review assortment before increasing sales pressure.", actions: ar ? ["حدد الأصناف المتوقفة.", "تحقق من التوفر الفعلي.", "اقترح صنفًا مكمّلًا واحدًا بعد التحقق."] : ["Identify dropped SKUs.", "Verify actual availability.", "Offer one complementary SKU after validation."] },
  };
  const plan = plans[focus];
  return { summary: ar ? `${labels[focus]} ${direction} ${pct(value)} في النطاق المحدد.` : `${labels[focus]} ${direction} by ${pct(value)} in the selected scope.`, evidence, interpretation: plan.interpretation, unknown: plan.unknown, confidence: ar ? "متوسطة" : "Medium", decision: plan.decision, actions: plan.actions };
}

// This is the single narrative layer used by the Team Performance deck. It
// consumes the same calculated metrics already rendered by the workspace;
// it does not query, aggregate, or infer unavailable operational data.
export function buildTeamExecutiveDiagnosis(dashboard: DashboardPerformance, locale: Locale, focus?: string): ExecutiveDiagnosis {
  if (focus?.startsWith("target:")) {
    const ar = locale === "ar"; const collection = focus.includes("Collection"); const target = dashboard.targets.find((item) => item.key === focus.slice(7)); const base = buildFocusedDiagnosis(dashboard, locale, collection ? "collections" : "sales"); const ahead = (target?.aheadBehind ?? 0) >= 0;
    return { ...base, summary: ar ? `${collection ? "هدف التحصيل" : "هدف المبيعات"} ${ahead ? "متقدم" : "متأخر"} عن المسار. ${base.summary}` : `${collection ? "Collection" : "Sales"} target is ${ahead ? "ahead of" : "behind"} plan. ${base.summary}`, decision: ar ? `${ahead ? "ثبّت" : "صحّح"} مسار الهدف: ${base.decision}` : `${ahead ? "Protect" : "Correct"} the target path: ${base.decision}` };
  }
  const normalizedFocus = focus?.startsWith("target:") ? (focus.includes("Collection") ? "collections" : "sales") : focus;
  if (["sales", "collections", "invoices", "customers", "skus", "returns"].includes(normalizedFocus ?? "")) return buildFocusedDiagnosis(dashboard, locale, normalizedFocus as DiagnosisFocus);
  const m = dashboard.metrics;
  const ar = locale === "ar";
  const avgInvoice = m.sales.growthPct !== null && m.invoices.growthPct !== null
    ? ((1 + m.sales.growthPct / 100) / Math.max(0.01, 1 + m.invoices.growthPct / 100) - 1) * 100 : null;
  const line = (label: string, value: number | null) => value === null ? null : `${label} ${pct(value)}`;
  const evidence = [line(ar ? "المبيعات" : "Sales", m.sales.growthPct), line(ar ? "العملاء" : "Customers", m.customers.growthPct), line(ar ? "الفواتير" : "Invoices", m.invoices.growthPct), line(ar ? "الأصناف" : "SKUs", m.skus.growthPct), line(ar ? "التحصيل" : "Collections", m.collections.growthPct), line(ar ? "المرتجعات" : "Returns", m.returns.growthPct), avgInvoice === null ? null : line(ar ? "متوسط الفاتورة" : "Average invoice", avgInvoice)].filter((x): x is string => Boolean(x));
  const comparableSignals = [m.sales.growthPct, m.collections.growthPct, m.customers.growthPct, m.invoices.growthPct, m.skus.growthPct, m.returns.growthPct].filter((value): value is number => value !== null).length;
  const positive = (m.sales.growthPct ?? 0) >= 0;
  // The narrative layer deliberately distinguishes evidence from a possible
  // operating cause. It stays shared by the UI and the executive deck.
  if (m.returns.growthPct !== null && m.returns.growthPct > 10) return { summary: ar ? "المرتجعات أصبحت عاملًا مؤثرًا في النتيجة." : "Returns are a material performance driver.", evidence, interpretation: ar ? "الارتفاع يدعم احتمال عدم ملاءمة الكمية أو التشكيلة؛ لا يثبت مشكلة جودة أو مخزون." : "The increase supports a possible quantity or assortment mismatch; it does not prove a quality or stock problem.", unknown: ar ? "لا يمكن إثبات التحميل الزائد أو سبب الجودة دون تفاصيل SKU والكمية وتكرار المرتجع." : "Overloading, quality, and a repeat-SKU pattern cannot be proven without SKU, quantity, and recurrence detail.", confidence: ar ? "متوسطة" : "Medium", decision: ar ? "عالج نمط المرتجعات قبل زيادة التحميل أو ضغط المبيعات." : "Resolve the returns pattern before increasing loading or sales pressure.", actions: ar ? ["راجع الأصناف أو العملاء الأكثر تكرارًا في المرتجعات.", "قارن الكمية الموردة بمعدل التصريف قبل إعادة التحميل.", "عدّل التحميل تدريجيًا بعد التحقق."] : ["Review the most recurrent returned SKUs or customers.", "Compare supplied quantity with sell-through before reloading.", "Adjust loading gradually after validation."] };
  if (comparableSignals < 2) return { summary: ar ? "البيانات المتاحة لا تكفي لتحديد سبب موثوق للأداء." : "Available data are insufficient to identify a reliable performance cause.", evidence, interpretation: ar ? "لا توجد مؤشرات مترابطة كافية لبناء تفسير." : "There are not enough connected indicators to support an interpretation.", unknown: ar ? "لا ينبغي افتراض سبب تشغيلي أو سلوك ميداني من مؤشر واحد." : "An operational cause or field behavior should not be assumed from one indicator.", confidence: ar ? "منخفضة" : "Low", decision: ar ? "استكمل البيانات قبل اتخاذ قرار تشغيلي كبير." : "Complete the evidence before making a material operating decision.", actions: ar ? ["راجع توفر بيانات المقارنة للفترة.", "استكمل بيانات الزيارات أو SKU عند الحاجة.", "أعد القياس في الفترة التالية."] : ["Check comparison-period availability.", "Complete visit or SKU data where needed.", "Reassess in the next period."] };
  if (m.sales.growthPct !== null && m.sales.growthPct < 0 && (m.collections.growthPct ?? 0) < 0) return { summary: ar ? "المبيعات والتحصيل يتراجعان معًا في النطاق المحدد." : "Sales and collections are declining together in the selected scope.", evidence, interpretation: ar ? "التزامن دليل على علاقة محتملة تحتاج مراجعة النطاق أو العملاء المتأثرين؛ لا يثبت السببية." : "The co-movement is evidence of a possible relationship that needs scope or customer review; it does not prove causation.", unknown: ar ? "لا يمكن إثبات أن العملاء المتعثرين في التحصيل هم أنفسهم المتراجعون في الشراء." : "The data do not prove that the customers behind collections weakness are the same customers buying less.", confidence: ar ? "متوسطة" : "Medium", decision: ar ? "أعطِ أولوية للتحصيل في النطاق المتعثر قبل التوسع الائتماني." : "Prioritize collections in the affected scope before expanding credit.", actions: ar ? ["راجع العملاء المتأخرين أولًا وحدد موعد تحصيل واضحًا.", "لا تضف ائتمانًا جديدًا قبل معالجة التعثر.", "أعد تقييم فرصة إعادة الطلب بعد التحصيل."] : ["Review overdue customers first and set a clear collection date.", "Avoid extending new credit before resolving delinquency.", "Reassess reorder opportunity after collection."] };
  if (m.sales.growthPct !== null && m.sales.growthPct > 0 && (m.customers.growthPct ?? 0) >= 0 && (m.invoices.growthPct ?? 0) >= 0) return { summary: ar ? "النمو مدعوم بنشاط العملاء والفواتير، وليس بالمبيعات وحدها." : "Growth is supported by customer and invoice activity, not sales alone.", evidence, interpretation: ar ? "النمط الإيجابي متسق مع تغطية أو إنتاجية أو عمق طلبية أفضل؛ لا تحدد البيانات أي سلوك ميداني بعينه." : "The positive pattern is consistent with stronger coverage, productivity, or basket depth; the data do not identify a specific field behavior.", unknown: ar ? "لا يمكن إثبات أي من هذه السلوكيات دون بيانات الزيارة أو العميل أو SKU." : "None of those behaviors can be proven without visit, customer, or SKU data.", confidence: ar ? "متوسطة" : "Medium", decision: ar ? "ثبّت الممارسة لدى الأفضل أداءً وانقلها بعد التحقق إلى النطاقات الأضعف." : "Codify the practice at top performers and transfer it to weaker scopes after validation.", actions: ar ? ["حدد أفضل الكيانات أداءً.", "استخرج الممارسة القابلة للتكرار من الزيارات الفعلية.", "راقب النمو مع ضبط المرتجعات."] : ["Identify top-performing entities.", "Extract the repeatable practice from actual visits.", "Track growth while guarding returns."] };
  if (m.sales.growthPct !== null && m.sales.growthPct < 0 && (m.customers.growthPct ?? 0) > 0 && (m.invoices.growthPct ?? 0) > 0 && (avgInvoice ?? 0) < 0) return { summary: ar ? "انخفاض المبيعات مرتبط بقيمة الطلبية أكثر من عدد العملاء أو الفواتير." : "Sales are down while customer and invoice activity grew; order depth is the strongest pressure point.", evidence, interpretation: ar ? "إشارة Basket Size هي الأقوى لأن متوسط الفاتورة تراجع رغم نمو العملاء والفواتير." : "Basket size is the strongest signal because average invoice value declined despite more customers and invoices.", unknown: ar ? "لا يمكن إثبات السعر أو توافر المخزون أو سبب الانخفاض داخل كل عميل من هذه البيانات." : "Price, stock availability, and the customer-level reason cannot be proven from these data.", confidence: ar ? "مرتفعة" : "High", decision: ar ? "لا نزيد الزيارات حاليًا؛ الأولوية لرفع متوسط الطلبية." : "Do not increase visits now; prioritize restoring average order depth.", actions: ar ? ["راجع الأصناف أو الكميات الناقصة في الطلبية.", "وجّه الاقتراح البيعي لطلبية محددة.", "راقب متوسط الفاتورة يوميًا."] : ["Review missing items or quantities in the basket.", "Coach toward a specific order proposal.", "Monitor average invoice value daily."] };
  if (m.sales.growthPct !== null && m.sales.growthPct < 0 && (m.customers.growthPct ?? 0) < 0) return { summary: ar ? "تراجع المبيعات يتزامن مع انخفاض العملاء المنتجين." : "Sales decline is moving with fewer productive customers.", evidence, interpretation: ar ? "تنشيط العملاء/التغطية سبب محتمل مدعوم باتجاه العملاء المنتجين." : "Customer activation or coverage is a supported likely driver.", unknown: ar ? "لا يمكن نسب الانخفاض إلى الزيارات دون بيانات زيارات فعلية." : "The cause cannot be attributed to visits without actual visit data.", confidence: ar ? "متوسطة" : "Medium", decision: ar ? "ابدأ باستعادة العملاء المتوقفين قبل توسيع النشاط." : "Recover stopped customers before expanding activity.", actions: ar ? ["حدد العملاء المتوقفين في النطاق المتراجع.", "راجع الرف قبل تقديم طلب محدد.", "تابع عودة العملاء في الفترة التالية."] : ["Identify stopped customers in the declining scope.", "Check the shelf before proposing a specific order.", "Track customer reactivation next period."] };
  if (m.returns.growthPct !== null && m.returns.growthPct > 10) return { summary: ar ? "المرتجعات أصبحت عاملًا مؤثرًا في النتيجة." : "Returns are a material performance driver.", evidence, interpretation: ar ? "تكرار ارتفاع المرتجعات يرجّح عدم ملاءمة كمية التحميل أو التشكيلة." : "Repeated return growth suggests quantity or assortment mismatch.", unknown: ar ? "لا يمكن إثبات تحميل زائد أو سبب جودة دون تفاصيل SKU والكمية." : "Overloading or a quality cause cannot be proven without SKU and quantity detail.", confidence: ar ? "متوسطة" : "Medium", decision: ar ? "عالج نمط المرتجعات قبل زيادة التحميل أو المبيعات." : "Resolve the returns pattern before increasing loading or sales pressure.", actions: ar ? ["راجع أكثر الأصناف تكرارًا في المرتجعات.", "قارن الكمية الموردة بمعدل التصريف.", "عدّل التحميل تدريجيًا بعد التحقق."] : ["Review the most recurrent returned SKUs.", "Compare supplied quantity with sell-through.", "Adjust loading gradually after validation."] };
  if (positive) return { summary: ar ? "الأداء يتحسن في النطاق المحدد." : "Performance is improving in the selected scope.", evidence, interpretation: ar ? "المؤشرات المتاحة تدعم نتيجة إيجابية؛ حافظ على الممارسة عند أفضل الكيانات." : "Available indicators support a positive outcome; preserve the practice at the best entities.", unknown: ar ? "لا تثبت البيانات وحدها السلوك الميداني الذي سبب التحسن." : "The data alone do not prove the field behavior behind the improvement.", confidence: ar ? "متوسطة" : "Medium", decision: ar ? "ثبّت ما يعمل وانقله إلى الكيانات الأقل أداءً." : "Codify what works and transfer it to lower-performing entities.", actions: ar ? ["حدد أفضل الكيانات أداءً.", "استخرج الممارسة القابلة للتكرار.", "تابع استمرار النمو دون رفع المرتجعات."] : ["Identify top-performing entities.", "Extract the repeatable practice.", "Track growth without increasing returns."] };
  return { summary: ar ? "لا توجد إشارة مترابطة كافية لتحديد سبب موثوق." : "There is not enough connected evidence for a reliable root cause.", evidence, interpretation: ar ? "المؤشرات المتاحة لا تدعم تفسيرًا واحدًا واضحًا." : "Available metrics do not support one clear explanation.", unknown: ar ? "لا ينبغي افتراض سبب تشغيلي دون بيانات إضافية." : "An operational cause should not be assumed without additional data.", confidence: ar ? "منخفضة" : "Low", decision: ar ? "اعرض المؤشرات المتاحة واستكمل البيانات قبل قرار تشغيلي كبير." : "Review available indicators and complete the evidence before a major operating decision.", actions: ar ? ["راجع الكيانات الأكثر تأثيرًا.", "استكمل بيانات الزيارات أو SKU عند الحاجة.", "أعد القياس في الفترة التالية."] : ["Review the most influential entities.", "Complete visit or SKU data where needed.", "Reassess in the next period."] };
}

async function generateArabicExecutivePptx(input: TeamExecutiveDeckInput): Promise<number> {
  const PptxGenJS = (await import("pptxgenjs")).default; const pptx = new PptxGenJS(); pptx.layout = "LAYOUT_WIDE"; (pptx as unknown as { rtlMode?: boolean }).rtlMode = true;
  const diagnosis = buildTeamExecutiveDiagnosis(input.dashboard, "ar"); const m = input.dashboard.metrics; const money = (value: number | null) => value === null ? "—" : `${Math.round(value).toLocaleString("en-US")} ر.س.`; const number = (value: number | null) => value === null ? "—" : Math.round(value).toLocaleString("en-US");
  const visualRtl = (value: string) => /[\u0600-\u06FF]/.test(value) ? value.split(/(\s+)/).reverse().join("") : value;
  const addText = (slide: ReturnType<typeof pptx.addSlide>, value: string, x: number, y: number, w: number, h: number, size: number, color = colors.ink, bold = false, numeric = false) => slide.addText(numeric ? value : visualRtl(value), { x, y, w, h, margin: 0, fontFace: "Arial", fontSize: size, color, bold, align: numeric ? "left" : "right", rtlMode: false, breakLine: false, fit: "shrink" });
  const chrome = (slide: ReturnType<typeof pptx.addSlide>, title: string, subtitle?: string) => { slide.background = { color: colors.navy }; slide.addShape("rect", { x: 0, y: 0, w: 13.33, h: .06, fill: { color: colors.blue }, line: { color: colors.blue, width: 0 } }); slide.addText(visualRtl(title), { x: .65, y: .50, w: 12, h: .65, margin: .08, fontFace: "Arial", fontSize: 28, color: colors.ink, bold: true, align: "right", rtlMode: false, breakLine: false, fit: "shrink" }); if (subtitle) addText(slide, subtitle, .65, 1.12, 12, .24, 12, colors.muted); addText(slide, "Murshidak | Field Sales OS", .65, 7.06, 12, .15, 8, colors.muted); };
  const card = (slide: ReturnType<typeof pptx.addSlide>, x: number, y: number, w: number, h: number, label: string, value: string, delta?: number | null, lower = false) => { slide.addShape("roundRect", { x, y, w, h, rectRadius: .08, fill: { color: colors.surface, transparency: 3 }, line: { color: colors.line, width: .5 } }); addText(slide, label, x + .22, y + .18, w - .44, .2, 11, colors.muted); addText(slide, value, x + .22, y + .52, w - .44, .32, 21, colors.ink, true, true); if (delta !== undefined) addText(slide, pct(delta), x + .22, y + 1.02, w - .44, .16, 10, tone(delta, lower), true, true); };
  { const slide = pptx.addSlide(); chrome(slide, "مراجعة أداء الفريق", input.scopeLabel); addText(slide, input.companyName, .7, 2.15, 11.9, .35, 18, colors.pale, true); addText(slide, "الفترة الحالية", .7, 3.15, 12, .18, 12, colors.muted); addText(slide, `${input.currentPeriod.to}  إلى  ${input.currentPeriod.from}`, .7, 3.47, 12, .25, 16, colors.ink, true, true); addText(slide, "فترة المقارنة", .7, 4.15, 12, .18, 12, colors.muted); addText(slide, input.referencePeriod ? `${input.referencePeriod.to}  إلى  ${input.referencePeriod.from}` : "لا توجد فترة مقارنة", .7, 4.47, 12, .25, 16, colors.ink, true, true); }
  { const slide = pptx.addSlide(); chrome(slide, "اللقطة التنفيذية", "ماذا حدث في النطاق المحدد؟"); [["المبيعات", money(m.sales.current), m.sales.growthPct, false], ["التحصيل", money(m.collections.current), m.collections.growthPct, false], ["العملاء المشترون", number(m.customers.current), m.customers.growthPct, false], ["الفواتير", number(m.invoices.current), m.invoices.growthPct, false], ["الأصناف المباعة", number(m.skus.current), m.skus.growthPct, false], ["المرتجعات", money(m.returns.current), m.returns.growthPct, true]].forEach(([label, value, delta, lower], i) => card(slide, .65 + (i % 3) * 4.05, 1.45 + Math.floor(i / 3) * 1.6, 3.7, 1.32, String(label), String(value), delta as number | null, Boolean(lower))); }
  { const slide = pptx.addSlide(); chrome(slide, "محركات التغير", "ما الذي تحرك مقارنة بالفترة المرجعية؟"); const items = [["المبيعات", m.sales.growthPct], ["التحصيل", m.collections.growthPct], ["العملاء", m.customers.growthPct], ["الفواتير", m.invoices.growthPct], ["الأصناف", m.skus.growthPct], ["المرتجعات", m.returns.growthPct]]; items.forEach(([label, delta], i) => card(slide, .65 + (i % 2) * 6.05, 1.45 + Math.floor(i / 2) * 1.35, 5.7, 1.05, String(label), pct(delta as number | null), undefined)); addText(slide, "تُعرض المؤشرات كأدلة؛ ولا تُحوَّل العلاقة إلى سبب مثبت دون بيانات داعمة.", .65, 5.85, 11.7, .35, 15, colors.pale, true); }
  { const slide = pptx.addSlide(); chrome(slide, "الأداء مقابل الهدف", "أين نقف حتى اليوم؟"); input.dashboard.targets.filter((target) => target.primary).slice(0, 2).forEach((target, i) => { const x = .65 + i * 6.05; slide.addShape("roundRect", { x, y: 1.42, w: 5.7, h: 4.75, rectRadius: .08, fill: { color: colors.surface }, line: { color: colors.line, width: .5 } }); addText(slide, target.label, x + .24, 1.72, 5.2, .3, 21, colors.ink, true); [["المحقق", target.actualMtd], ["الهدف حتى اليوم", target.targetMtd], ["الفجوة", target.aheadBehind], ["نسبة الإنجاز", target.progressPct], ["المطلوب يوميًا", target.requiredDailyVelocity], ["توقع نهاية الشهر", target.runRateForecast]].forEach(([label, value], row) => { addText(slide, String(label), x + 3, 2.35 + row * .53, 2.2, .18, 11, colors.muted); const percent = row === 3; addText(slide, percent ? `${Number(value).toFixed(1)}%` : money(value as number | null), x + .25, 2.31 + row * .53, 2.55, .25, 16, row === 2 ? tone(value as number | null) : colors.ink, true, true); }); }); }
  { const slide = pptx.addSlide(); chrome(slide, "التشخيص التنفيذي", "لماذا حدث ذلك؟"); const sections: [string, string, string][] = [["الخلاصة", diagnosis.summary, colors.blue], ["الأدلة", diagnosis.evidence.join(" • "), colors.pale], ["السبب المحتمل", diagnosis.interpretation, colors.amber], ["ما لا يمكن إثباته", diagnosis.unknown, colors.muted], ["درجة الثقة", diagnosis.confidence, colors.green]]; sections.forEach(([label, body, color], i) => { addText(slide, label, 9.6, 1.45 + i * .88, 2.3, .18, 13, color, true); addText(slide, body, .85, 1.4 + i * .88, 8.4, .45, i === 0 ? 21 : 15, i === 0 ? colors.ink : colors.pale, i === 0); }); }
  { const slide = pptx.addSlide(); chrome(slide, "القرار وخطة التنفيذ", "ماذا نفعل الآن؟"); addText(slide, diagnosis.decision, .7, 1.52, 11.9, .52, 21, colors.ink, true); diagnosis.actions.slice(0, 3).forEach((action, i) => { const x = .65 + i * 4.05; slide.addShape("roundRect", { x, y: 2.85, w: 3.7, h: 1.75, rectRadius: .08, fill: { color: colors.surface }, line: { color: colors.line, width: .5 } }); addText(slide, `0${i + 1}`, x + .2, 3.1, 3.25, .18, 12, colors.blue, true); addText(slide, action, x + .2, 3.6, 3.25, .55, 16, colors.pale, true); }); }
  const safeScope = input.scopeLabel.replace(/[\\/:*?"<>|]/g, "").trim() || "team-performance"; await pptx.writeFile({ fileName: `مراجعة-تنفيذية-${safeScope}.pptx` }); return 6;
}

export async function generateTeamExecutivePptx(input: TeamExecutiveDeckInput): Promise<number> {
  if (input.locale === "ar") return generateArabicExecutivePptx(input);
  const PptxGenJS = (await import("pptxgenjs")).default;
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "Murshidak | Field Sales OS";
  pptx.subject = "Executive Team Performance Review";
  (pptx as unknown as { rtlMode?: boolean }).rtlMode = false;
  const c = copy("en"); const rtl = false; const align = "left" as const;
  const diagnosis = buildTeamExecutiveDiagnosis(input.dashboard, input.locale);
  let slides = 0;
  const chrome = (slide: ReturnType<typeof pptx.addSlide>, dark = true) => { slide.background = { color: dark ? colors.navy : "FFFFFF" }; slide.addShape("rect", { x: 0, y: 0, w: 13.33, h: 0.06, fill: { color: colors.blue }, line: { color: colors.blue, width: 0 } }); slide.addText(c.powered, { x: 0.55, y: 7.05, w: 12.2, h: 0.18, fontFace: "Arial", fontSize: 8, color: dark ? colors.muted : "64748B", align, margin: 0 }); };
  const text = (slide: ReturnType<typeof pptx.addSlide>, value: string, x: number, y: number, w: number, h: number, size: number, options: { color?: string; bold?: boolean; align?: "left" | "right" | "center" } = {}) => slide.addText(value, { x, y, w, h, fontFace: "Arial", fontSize: size, color: options.color ?? colors.ink, bold: options.bold ?? false, align: options.align ?? align, margin: 0, breakLine: false, fit: "shrink", rtlMode: rtl });
  const display = (value: number | null, currency = false) => format(value, currency, rtl);
  const addTitle = (slide: ReturnType<typeof pptx.addSlide>, title: string, subtitle?: string) => { text(slide, title, 0.65, 0.42, 12.0, 0.42, 27, { bold: true }); if (subtitle) text(slide, subtitle, 0.65, 0.9, 12.0, 0.25, 11, { color: colors.muted }); };
  const addMetric = (slide: ReturnType<typeof pptx.addSlide>, x: number, y: number, label: string, value: string, delta?: number | null, lowerBetter = false) => { slide.addShape("roundRect", { x, y, w: 2.92, h: 1.25, rectRadius: 0.08, fill: { color: colors.surface, transparency: 8 }, line: { color: colors.line, width: 0.5 } }); text(slide, label, x + .18, y + .16, 2.55, .18, 10, { color: colors.muted }); text(slide, value, x + .18, y + .48, 2.55, .3, 19, { bold: true }); if (delta !== undefined) text(slide, pct(delta), x + .18, y + .93, 2.55, .16, 9, { color: tone(delta, lowerBetter), bold: true }); };
  const periodLabel = `${input.currentPeriod.from} → ${input.currentPeriod.to}`;
  const refLabel = input.referencePeriod ? `${input.referencePeriod.from} → ${input.referencePeriod.to}` : "—";

  { const slide = pptx.addSlide(); slides++; chrome(slide); text(slide, "MURSHIDAK", .7, 1.15, 11.9, .35, 16, { color: colors.blue, bold: true }); text(slide, c.title, .7, 1.8, 11.9, .7, 38, { bold: true }); text(slide, input.companyName, .7, 2.72, 11.9, .32, 16, { color: colors.pale }); text(slide, input.scopeLabel, .7, 3.15, 11.9, .26, 13, { color: colors.muted }); slide.addShape("rect", { x: .7, y: 3.72, w: 11.9, h: .02, fill: { color: colors.line }, line: { color: colors.line, width: 0 } }); text(slide, `${c.period}: ${periodLabel}`, .7, 4.0, 11.9, .25, 13, { color: colors.pale }); text(slide, `${c.referencePeriod}: ${refLabel}`, .7, 4.36, 11.9, .25, 13, { color: colors.pale }); text(slide, `${c.generated}: ${new Date().toLocaleDateString("en-GB")}`, .7, 4.72, 11.9, .2, 11, { color: colors.muted }); }
  { const slide = pptx.addSlide(); slides++; chrome(slide); addTitle(slide, c.snapshot, input.scopeLabel); const m = input.dashboard.metrics; const metrics: [string, string, number | null, boolean][] = [[c.sales, format(m.sales.current, true), m.sales.growthPct, false], [c.collections, format(m.collections.current, true), m.collections.growthPct, false], [c.customers, format(m.customers.current), m.customers.growthPct, false], [c.invoices, format(m.invoices.current), m.invoices.growthPct, false], [c.skus, format(m.skus.current), m.skus.growthPct, false], [c.returns, format(m.returns.current, true), m.returns.growthPct, true]]; metrics.forEach(([label, value, delta, lower], i) => addMetric(slide, .65 + (i % 3) * 4.05, 1.45 + Math.floor(i / 3) * 1.5, label, value, delta, lower)); const targets = input.dashboard.targets.filter((target) => target.primary).slice(0, 2); targets.forEach((target, i) => { const progressDelta = target.aheadBehind === null || !target.targetMtd ? null : (target.aheadBehind / target.targetMtd) * 100; addMetric(slide, .65 + i * 4.05, 4.65, target.label, target.progressPct === null ? "—" : `${target.progressPct.toFixed(0)}%`, progressDelta, false); }); const signals = diagnosis.evidence.slice(0, 3).join("  •  "); text(slide, signals || c.noData, .65, 6.25, 12.0, .3, 12, { color: colors.pale, bold: true }); }
  { const slide = pptx.addSlide(); slides++; chrome(slide); addTitle(slide, c.story); const columns = [{ title: c.fact, body: diagnosis.summary, color: colors.blue }, { title: c.interpretation, body: diagnosis.interpretation, color: colors.amber }, { title: c.unknown, body: diagnosis.unknown, color: colors.muted }]; columns.forEach((item, i) => { const x = .65 + i * 4.05; slide.addShape("roundRect", { x, y: 1.55, w: 3.7, h: 4.65, rectRadius: .08, fill: { color: colors.surface, transparency: 5 }, line: { color: colors.line, width: .5 } }); slide.addShape("rect", { x, y: 1.55, w: .06, h: 4.65, fill: { color: item.color }, line: { color: item.color, width: 0 } }); text(slide, item.title, x + .25, 1.86, 3.1, .28, 16, { bold: true, color: item.color }); text(slide, item.body, x + .25, 2.42, 3.05, 2.8, 17, { color: colors.pale }); }); }
  const trendMetrics = ["sales", "collections", "customers", "invoices"].map((key) => ({ key, metric: input.dashboard.metrics[key as keyof DashboardPerformance["metrics"]] })).filter((x) => x.metric.current !== null && x.metric.benchmark !== null);
  if (trendMetrics.length > 0) { const slide = pptx.addSlide(); slides++; chrome(slide); addTitle(slide, c.growth, `${c.current} vs ${c.reference}`); slide.addChart("bar", [{ name: c.current, labels: trendMetrics.map((x) => ({ sales: c.sales, collections: c.collections, customers: c.customers, invoices: c.invoices }[x.key]!)), values: trendMetrics.map((x) => x.metric.current ?? 0) }, { name: c.reference, labels: trendMetrics.map((x) => ({ sales: c.sales, collections: c.collections, customers: c.customers, invoices: c.invoices }[x.key]!)), values: trendMetrics.map((x) => x.metric.benchmark ?? 0) }], { x: .75, y: 1.45, w: 7.4, h: 4.95, catAxisLabelColor: colors.pale, valAxisLabelColor: colors.muted, chartColors: [colors.blue, colors.muted], showLegend: true, legendPos: "b", showTitle: false, showValue: false, valGridLine: { color: colors.line } }); text(slide, diagnosis.summary, 8.65, 1.8, 3.95, 1.1, 20, { bold: true }); text(slide, diagnosis.evidence.slice(0, 4).join("\n"), 8.65, 3.35, 3.95, 1.8, 14, { color: colors.pale }); text(slide, `${c.confidence}: ${diagnosis.confidence}`, 8.65, 5.72, 3.95, .25, 12, { color: colors.amber, bold: true }); }
  const primaryTargets = input.dashboard.targets.filter((target) => target.primary);
  if (primaryTargets.length > 0) { const slide = pptx.addSlide(); slides++; chrome(slide); addTitle(slide, c.targets); primaryTargets.slice(0, 2).forEach((target, i) => { const x = .65 + i * 6.05; slide.addShape("roundRect", { x, y: 1.5, w: 5.75, h: 4.85, rectRadius: .08, fill: { color: colors.surface, transparency: 5 }, line: { color: colors.line, width: .5 } }); text(slide, target.label, x + .25, 1.78, 5.2, .3, 20, { bold: true }); const rows: [string, string][] = [[c.actual, format(target.actualMtd, target.unit === "currency")], [c.targetToDate, format(target.targetMtd, target.unit === "currency")], [c.gap, signed(target.aheadBehind, target.unit === "currency")], [c.achievement, target.progressPct === null ? "—" : `${target.progressPct.toFixed(1)}%`], [c.required, format(target.requiredDailyVelocity, target.unit === "currency")], [c.forecast, format(target.runRateForecast, target.unit === "currency")]]; rows.forEach(([label, value], row) => { text(slide, label, x + .25, 2.42 + row * .47, 2.7, .2, 11, { color: colors.muted }); text(slide, value, x + 2.8, 2.42 + row * .47, 2.65, .2, 13, { bold: true, align: rtl ? "left" : "right", color: row === 2 ? tone(target.aheadBehind) : colors.ink }); }); }); }
  if (input.compareMode && input.reps.length > 1) { const sorted = input.reps.filter((rep) => rep.sales !== null).slice().sort((a, b) => ((b.sales ?? 0) - (b.salesPrior ?? 0)) / Math.max(1, b.salesPrior ?? 1) - ((a.sales ?? 0) - (a.salesPrior ?? 0)) / Math.max(1, a.salesPrior ?? 1)); if (sorted.length > 0) { const slide = pptx.addSlide(); slides++; chrome(slide); addTitle(slide, c.comparison, `${c.top}: ${sorted[0]?.repName ?? "—"}  |  ${c.risk}: ${sorted.at(-1)?.repName ?? "—"}`); const rows = sorted.slice(0, 8); const cell = (value: string, bold = false) => ({ text: value, options: { bold, color: colors.ink, align: "center" as const, fontFace: "Arial", fontSize: 14 } }); slide.addTable([[cell(c.entity, true), cell(c.sales, true), cell(c.collections, true), cell(c.returns, true), cell(c.salesDelta, true)], ...rows.map((rep) => [cell(rep.repName, true), cell(format(rep.sales, true)), cell(format(rep.collection, true)), cell(format(rep.returns, true)), cell(rep.salesPrior && rep.sales !== null ? pct(((rep.sales - rep.salesPrior) / rep.salesPrior) * 100) : "—")])], { x: .7, y: 1.5, w: 11.9, colW: [3.3, 2.1, 2.1, 2.1, 2.3], border: { type: "solid", color: colors.line, pt: .5 }, fill: { color: colors.surface }, color: colors.ink, fontFace: "Arial", fontSize: 14, margin: 5, rowH: .45, bold: false }); } }
  { const slide = pptx.addSlide(); slides++; chrome(slide); addTitle(slide, c.diagnosis); const fields: [string, string, string][] = [["", diagnosis.summary, colors.blue], [c.evidence, diagnosis.evidence.join("  •  ") || c.noData, colors.pale], [c.interpretation, diagnosis.interpretation, colors.amber], [c.unknown, diagnosis.unknown, colors.muted], [c.confidence, diagnosis.confidence, colors.green]]; fields.forEach(([label, value, color], i) => { const y = 1.45 + i * .94; if (label) text(slide, label, .75, y, 2.4, .2, 12, { color, bold: true }); text(slide, value, label ? 3.1 : .75, y, label ? 9.3 : 11.6, .52, i === 0 ? 22 : 15, { color: i === 0 ? colors.ink : colors.pale, bold: i === 0 }); }); }
  { const slide = pptx.addSlide(); slides++; chrome(slide); addTitle(slide, c.decision); text(slide, diagnosis.decision, .75, 1.55, 11.8, .75, 25, { bold: true, color: colors.pale }); slide.addShape("rect", { x: .75, y: 2.68, w: 11.8, h: .02, fill: { color: colors.line }, line: { color: colors.line, width: 0 } }); text(slide, c.actions, .75, 3.08, 11.8, .3, 17, { color: colors.blue, bold: true }); diagnosis.actions.slice(0, 3).forEach((action, i) => { const x = .75 + i * 4; slide.addShape("roundRect", { x, y: 3.7, w: 3.62, h: 1.55, rectRadius: .08, fill: { color: colors.surface, transparency: 5 }, line: { color: colors.line, width: .5 } }); text(slide, String(i + 1).padStart(2, "0"), x + .2, 3.95, 3.2, .25, 12, { color: colors.blue, bold: true }); text(slide, action, x + .2, 4.38, 3.2, .52, 15, { color: colors.pale, bold: true }); }); }
  const safeScope = input.scopeLabel.replace(/[\\/:*?"<>|]/g, "").trim() || "team-performance";
  await pptx.writeFile({ fileName: `executive-review-${safeScope}.pptx` });
  return slides;
}
