"use client";
import { useQuery } from "@tanstack/react-query";
import { Activity, AlertTriangle, Building2, ChevronDown, ChevronRight, FolderTree, Search, ShieldCheck, UserRound, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { userActivityApi } from "@/lib/api";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

type Person = any; type Node = { id: string; label: string; kind: "company" | "org" | "group" | "user"; people?: Person[]; person?: Person; children: Node[] };
const groupFor = (u: Person) => u.role?.code === "MANAGER" ? "Managers" : u.role?.code === "SUPERVISOR" ? "Supervisors" : u.role?.code === "SALES_REP" ? "Sales Reps" : "Other Users";
function buildTree(users: Person[]): Node[] { const companies = new Map<string, Node>(); const orgs = new Map<string, Node>();
  for (const u of users) { const cid = u.company?.id ?? "platform"; if (!companies.has(cid)) companies.set(cid, { id: `c:${cid}`, label: u.company?.name ?? "Platform", kind: "company", children: [] }); if (u.orgUnit && !orgs.has(u.orgUnit.id)) orgs.set(u.orgUnit.id, { id: `o:${u.orgUnit.id}`, label: u.orgUnit.name, kind: "org", children: [] }); }
  for (const org of orgs.values()) { const sample = users.find(u => u.orgUnit?.id === org.id); const parent = sample?.orgUnit?.parentId ? orgs.get(sample.orgUnit.parentId) : undefined; (parent ?? companies.get(sample?.company?.id ?? "platform")!).children.push(org); }
  const buckets = new Map<string, Person[]>(); for (const u of users) { const owner = u.orgUnit ? `o:${u.orgUnit.id}` : `c:${u.company?.id ?? "platform"}`; const key = `${owner}:${groupFor(u)}`; buckets.set(key, [...(buckets.get(key) ?? []), u]); }
  for (const [key, people] of buckets) { const ownerId = key.slice(0, key.lastIndexOf(":")); const label = key.slice(key.lastIndexOf(":") + 1); const owner = [...companies.values(), ...orgs.values()].find(n => n.id === ownerId)!; owner.children.push({ id: `g:${key}`, label, kind: "group", people, children: people.sort((a,b) => a.fullName.localeCompare(b.fullName)).map(person => ({ id: `u:${person.id}`, label: person.fullName, kind: "user", person, children: [] })) }); }
  const sort = (n: Node[]) => { n.sort((a,b) => a.label.localeCompare(b.label)); n.forEach(x => sort(x.children)); }; const root = [...companies.values()]; sort(root); return root; }
function ancestors(nodes: Node[], userId: string, path: string[] = []): string[] | null { for (const n of nodes) { const next = [...path,n.id]; if(n.person?.id === userId) return next; const hit=ancestors(n.children,userId,next); if(hit)return hit; } return null; }

export default function UserActivityCenterPage() { const [query,setQuery]=useState(""); const [selected,setSelected]=useState<string>(); const [expanded,setExpanded]=useState<Set<string>>(new Set()); const [from,setFrom]=useState(""); const [to,setTo]=useState("");
  const tree=useQuery({queryKey:["user-activity","tree"],queryFn:userActivityApi.tree}); const search=useQuery({queryKey:["user-activity","search",query],queryFn:()=>userActivityApi.search(query),enabled:query.trim().length>1}); const timeline=useQuery({queryKey:["user-activity","timeline",selected,from,to],queryFn:()=>userActivityApi.timeline(selected!,from||undefined,to||undefined),enabled:!!selected});
  const nodes=useMemo(()=>buildTree(tree.data??[]),[tree.data]); const allIds=useMemo(()=>{const ids:string[]=[];const walk=(ns:Node[])=>ns.forEach(n=>{ids.push(n.id);walk(n.children)});walk(nodes);return ids},[nodes]); const selectedUser=(tree.data??[]).find((u:Person)=>u.id===selected);
  useEffect(()=>setExpanded(new Set(allIds.filter(id=>!id.startsWith("u:")))),[allIds]); useEffect(()=>{const hit=search.data?.[0];if(hit){const path=ancestors(nodes,hit.id);if(path){setExpanded(p=>new Set([...p,...path]));setSelected(hit.id)}}},[search.data,nodes]);
  useEffect(() => { const heading = document.querySelector("h1"); if (heading) heading.textContent = "مركز نشاط المستخدمين"; const layout = document.querySelector(".grid.gap-5.lg\\:grid-cols-\\[390px_1fr\\]") as HTMLElement | null; if (layout) layout.style.gridTemplateColumns = "minmax(520px, 42%) minmax(0, 1fr)"; }, []);
  const choose=(id:string)=>{const path=ancestors(nodes,id);if(path)setExpanded(p=>new Set([...p,...path]));setSelected(id);setQuery("")}; const toggleAll=()=>setExpanded(p=>p.size?new Set():new Set(allIds.filter(id=>!id.startsWith("u:"))));
  return <div className="space-y-5"><div><h1 className="text-2xl font-semibold">User Activity Center</h1><p className="text-muted-foreground">Operational and security activity, scoped to your organizational tree.</p></div><div className="grid gap-5 lg:grid-cols-[390px_1fr]"><Card><CardHeader><div className="flex items-center justify-between"><CardTitle className="flex items-center gap-2"><FolderTree className="h-5 w-5"/>Group Tree</CardTitle><Button variant="outline" size="sm" onClick={toggleAll}>{expanded.size?"Collapse all":"Expand all"}</Button></div><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or email"/></div></CardHeader><CardContent className="max-h-[65vh] overflow-auto">{nodes.map(n=><TreeNode key={n.id} node={n} expanded={expanded} setExpanded={setExpanded} selected={selected} onChoose={choose}/>)}</CardContent></Card><div className="space-y-4">{selectedUser?<><UserContext user={selectedUser} users={tree.data??[]}/><div className="flex gap-2"><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Total Events",timeline.data?.summary.totalEvents,Activity],["Business",timeline.data?.summary.businessEvents,Activity],["Denied",timeline.data?.summary.deniedEvents,AlertTriangle],["Security Alerts",timeline.data?.summary.securityAlerts,ShieldCheck],["Risk Level",timeline.data?.summary.riskLevel,ShieldCheck]].filter(([l,v])=>v!==undefined||!['Security Alerts','Risk Level'].includes(l as string)).map(([l,v,I]: any) => <Card key={l}><CardContent className="flex justify-between p-4 text-sm"><span>{l}</span><span className="font-semibold"><I className="mr-1 inline h-4 w-4"/>{v??"—"}</span></CardContent></Card>)}</div><Card><CardHeader><CardTitle>Timeline</CardTitle></CardHeader><CardContent className="space-y-3">{timeline.data?.items?.map((e:any)=><div key={e.id} className="border-l-2 pl-3"><div className="flex justify-between"><b>{e.type}</b><time className="text-xs text-muted-foreground">{new Date(e.timestamp).toLocaleString()}</time></div><p className="text-sm text-muted-foreground">{e.category} · {e.outcome} · {e.source}</p></div>)}</CardContent></Card></>:<Card><CardContent className="p-10 text-center text-muted-foreground">Choose a user from the Group Tree to view their timeline.</CardContent></Card>}</div></div></div> }
function TreeNode({node,expanded,setExpanded,selected,onChoose}:{node:Node;expanded:Set<string>;setExpanded:React.Dispatch<React.SetStateAction<Set<string>>>;selected?:string;onChoose:(id:string)=>void}){const open=expanded.has(node.id), children=node.children.length>0, Icon=node.kind==='company'?Building2:node.kind==='user'?UserRound:node.kind==='group'?UsersRound:FolderTree;return <div className="text-sm"><div className={`flex items-center gap-1 rounded px-1 py-1 ${node.person?.id===selected?'bg-primary text-primary-foreground':'hover:bg-muted'}`}><Button variant="ghost" size="icon" className="h-6 w-6" disabled={!children} onClick={()=>setExpanded(p=>{const n=new Set(p);open?n.delete(node.id):n.add(node.id);return n})}>{children&&(open?<ChevronDown className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>)}</Button><button className="flex flex-1 items-center gap-2 text-left" onClick={()=>node.person?onChoose(node.person.id):children&&setExpanded(p=>new Set([...p,node.id]))}><Icon className="h-4 w-4"/><span className="truncate">{node.label}</span>{node.kind==='group'&&<span className="ml-auto text-xs opacity-70">{node.children.length}</span>}{node.person&&<span className="ml-auto text-xs opacity-70">{node.person.role?.code}</span>}</button></div>{open&&<div className="ml-4 border-l pl-2">{node.children.map(c=><TreeNode key={c.id} node={c} expanded={expanded} setExpanded={setExpanded} selected={selected} onChoose={onChoose}/>)}</div>}</div>}
function UserContext({user,users}:{user:Person;users:Person[]}){const byEmployee=new Map(users.filter(u=>u.employee).map(u=>[u.employee.id,u]));const direct=user.employee?.managerId?byEmployee.get(user.employee.managerId):undefined;const reports=users.filter(u=>u.employee?.managerId===user.employee?.id);const supervisor=direct?.role?.code==='SUPERVISOR'?direct:undefined;const manager=direct?.role?.code==='MANAGER'?direct:supervisor?.employee?.managerId?byEmployee.get(supervisor.employee.managerId):undefined;const extra=user.role?.code==='SUPERVISOR'?`${reports.length} Reps`:user.role?.code==='MANAGER'?`${users.filter(u=>u.role?.code==='SUPERVISOR'&&u.employee?.managerId===user.employee?.id).length} Supervisors · ${reports.filter(u=>u.role?.code==='SALES_REP').length} Reps`:undefined;return <Card><CardHeader><CardTitle>User Context</CardTitle></CardHeader><CardContent className="grid gap-3 text-sm sm:grid-cols-2 xl:grid-cols-4">{[["Name",user.fullName],["Role",user.role?.code],["Company",user.company?.name??"Platform"],["Branch / OrgUnit",user.orgUnit?.name??"Unassigned"],["Direct Supervisor",supervisor?.fullName??direct?.fullName??"—"],["Manager",manager?.fullName??"—"],["Status",user.status],["Team",extra??"—"]].map(([l,v])=><div key={l as string}><p className="text-muted-foreground">{l}</p><p className="font-medium">{v}</p></div>)}</CardContent></Card>}
