import type { RelationshipDefinition } from "./relationship-registry.types";

// RIE Graph Builder — Relationship Registry data.
//
// This is the machine-readable implementation of "FSOS Relationship
// Registry Specification v1.0". Every relationship below corresponds
// 1:1 to a relationship documented in that specification (same
// Relationship ID, same classification, same cardinality/direction/
// strength/lifecycle). The only change versus the specification
// document is representational, not architectural:
//
//   - Entity names here are the LITERAL plural forms from
//     FSOS_Canonical_Database_v1.0.xlsx ("_Canonical Model" sheet —
//     see canonical-entities.data.ts), e.g. "Customers" not "Customer".
//     The specification document used singular conceptual names for
//     readability; Graph Builder needs exact, unambiguous string
//     matches against the Canonical Database for its Unknown Entity
//     validation, so the plural canonical form is used here.
//   - "Navigation Rules" (free text in the spec) is expressed here as
//     a structured `navigation` object (foreignKey / allowed
//     navigation types / reverseAllowed / path / aggregationSources)
//     so it can be validated programmatically by Graph Builder and,
//     later, by Query Planner.
//
// No relationship's meaning was changed, no relationship was added,
// and none was removed relative to the specification document.

const SOT = "FSOS_Canonical_Database_v1.0.xlsx" as const;

export const RELATIONSHIP_REGISTRY: readonly RelationshipDefinition[] = [
  // ===================== ORG =====================
  {
    relationshipId: "REL-ORG-001",
    name: "Company_HasRegions",
    sourceEntity: "Companies",
    targetEntity: "Regions",
    relationshipType: "Structural",
    cardinality: "1:N",
    direction: "Companies -> Regions",
    strength: "Strong",
    lifecycle: "Active (governed by Region.Status)",
    timeAwareness: { isTimeAware: false, description: "No temporal dimension — fixed organizational relationship." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Regions.CompanyID", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["List every region belonging to Company X."],
    businessRuleConsumers: [],
    engineConsumers: ["Sales Team 360", "Executive Studio"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "ORG",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-ORG-002",
    name: "Region_HasBranches",
    sourceEntity: "Regions",
    targetEntity: "Branches",
    relationshipType: "Structural",
    cardinality: "1:N",
    direction: "Regions -> Branches",
    strength: "Strong",
    lifecycle: "Active (governed by Branch.Status)",
    timeAwareness: { isTimeAware: false, description: "No temporal dimension." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Branches.RegionID", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["List every branch belonging to Region X."],
    businessRuleConsumers: [],
    engineConsumers: ["Sales Team 360", "Route Intelligence", "Executive Studio"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "ORG",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-ORG-003",
    name: "Branch_HasEmployees",
    sourceEntity: "Branches",
    targetEntity: "Employees",
    relationshipType: "Structural",
    cardinality: "1:N",
    direction: "Branches -> Employees",
    strength: "Strong",
    lifecycle: "Active (governed by Employee.Status)",
    timeAwareness: { isTimeAware: false, description: "No temporal dimension." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Employees.BranchID", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["List every employee assigned to Branch X."],
    businessRuleConsumers: [],
    engineConsumers: ["Sales Team 360", "Customer 360"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "ORG",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-ORG-004",
    name: "Branch_HasRoutes",
    sourceEntity: "Branches",
    targetEntity: "Routes",
    relationshipType: "Structural",
    cardinality: "1:N",
    direction: "Branches -> Routes",
    strength: "Strong",
    lifecycle: "Active (governed by Route.Status)",
    timeAwareness: { isTimeAware: false, description: "No temporal dimension." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Routes.BranchID", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["List every route under Branch X."],
    businessRuleConsumers: ["Route Optimization", "Coverage Analysis"],
    engineConsumers: ["Route Intelligence", "Geo Intelligence"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "ORG",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-ORG-005",
    name: "Branch_HasCustomers",
    sourceEntity: "Branches",
    targetEntity: "Customers",
    relationshipType: "Structural",
    cardinality: "1:N",
    direction: "Branches -> Customers",
    strength: "Strong",
    lifecycle: "Active (governed by Customer.Status)",
    timeAwareness: { isTimeAware: false, description: "No temporal dimension." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Customers.BranchID", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["Count customers in Branch X."],
    businessRuleConsumers: ["Customer Classification"],
    engineConsumers: ["Customer 360", "Executive Studio"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "ORG",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-ORG-006",
    name: "Employee_ReportsTo",
    sourceEntity: "Employees",
    targetEntity: "Employees",
    relationshipType: "Structural",
    cardinality: "N:1 (self-referencing)",
    direction: "Employees -> Employees (Manager)",
    strength: "Strong",
    lifecycle: "Active (governed by Employee.Status)",
    timeAwareness: { isTimeAware: false, description: "Current-state only — no history of manager changes." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: {
      foreignKey: "Employees.DirectManagerID",
      allowedNavigationTypes: ["Direct", "Reverse"],
      reverseAllowed: true,
      path: null,
      aggregationSources: null,
    },
    queryExamples: ["Who is Employee X's direct manager?", "Who are Employee Y's direct reports?"],
    businessRuleConsumers: [],
    engineConsumers: ["Sales Team 360"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "ORG",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-ORG-007",
    name: "Route_HasAssignments",
    sourceEntity: "Routes",
    targetEntity: "Route Assignments",
    relationshipType: "Temporal",
    cardinality: "1:N",
    direction: "Routes -> Route Assignments",
    strength: "Strong",
    lifecycle: "Active / Historical / Expired (via RouteAssignment.Status + StartDate/EndDate)",
    timeAwareness: { isTimeAware: true, description: "Primary temporal relationship in the entire registry." },
    snapshotBehavior: { isSnapshot: false, description: "This is the live historical relationship itself, not a Snapshot." },
    navigation: {
      foreignKey: "Route Assignments.RouteID",
      allowedNavigationTypes: ["Direct", "Context", "Temporal"],
      reverseAllowed: true,
      path: null,
      aggregationSources: null,
    },
    queryExamples: ["Who was responsible for Route X on 2026-03-01?"],
    businessRuleConsumers: [],
    engineConsumers: ["Route Intelligence", "Sales Team 360"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "ORG",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-ORG-008",
    name: "Employee_HasAssignments",
    sourceEntity: "Employees",
    targetEntity: "Route Assignments",
    relationshipType: "Temporal",
    cardinality: "1:N",
    direction: "Employees -> Route Assignments",
    strength: "Strong",
    lifecycle: "Active / Historical / Expired",
    timeAwareness: { isTimeAware: true, description: "Primary temporal relationship." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: {
      foreignKey: "Route Assignments.EmployeeID",
      allowedNavigationTypes: ["Direct", "Context", "Temporal"],
      reverseAllowed: true,
      path: null,
      aggregationSources: null,
    },
    queryExamples: ["Which routes did Employee X manage during 2025?"],
    businessRuleConsumers: [],
    engineConsumers: ["Sales Team 360", "Executive Studio"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "ORG",
    sourceOfTruth: SOT,
  },

  // ===================== RT =====================
  {
    relationshipId: "REL-RT-001",
    name: "Route_HasCustomers",
    sourceEntity: "Routes",
    targetEntity: "Customers",
    relationshipType: "Structural",
    cardinality: "1:N",
    direction: "Routes -> Customers",
    strength: "Strong",
    lifecycle: "Active (governed by Customer.Status)",
    timeAwareness: { isTimeAware: false, description: "Current-state only." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Customers.RouteID", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["List Route X's customers ordered by VisitSequence."],
    businessRuleConsumers: ["Coverage Analysis", "Visit Priority"],
    engineConsumers: ["Route Intelligence", "Geo Intelligence", "Customer 360"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "RT",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-RT-002",
    name: "Route_HasVisits",
    sourceEntity: "Routes",
    targetEntity: "Visits",
    relationshipType: "Snapshot",
    cardinality: "1:N",
    direction: "Routes -> Visits",
    strength: "Strong",
    lifecycle: "Active (permanent historical record, never deleted)",
    timeAwareness: { isTimeAware: true, description: "VisitDate anchors this relationship." },
    snapshotBehavior: {
      isSnapshot: true,
      description: "Visits.RouteID reflects the route as it actually was at visit time — never re-derived via Route Assignment.",
    },
    navigation: { foreignKey: "Visits.RouteID", allowedNavigationTypes: ["Direct", "Context", "Snapshot"], reverseAllowed: false, path: null, aggregationSources: null },
    queryExamples: ["All visits on Route X during March 2026."],
    businessRuleConsumers: ["Visit Priority", "Coverage Analysis", "Strike Rate"],
    engineConsumers: ["Route Intelligence", "SGI", "Murshidak"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "RT",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-RT-003",
    name: "Customer_HasVisits",
    sourceEntity: "Customers",
    targetEntity: "Visits",
    relationshipType: "Operational",
    cardinality: "1:N",
    direction: "Customers -> Visits",
    strength: "Strong",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: true, description: "VisitDate compared against Customer.VisitDay/VisitSequence to determine Planned/Extra." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Visits.CustomerCode", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["Last 5 visits to Customer X and each visit's status."],
    businessRuleConsumers: ["Visit Priority", "Customer Health"],
    engineConsumers: ["Customer 360", "SGI", "Murshidak"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "RT",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-RT-004",
    name: "Visit_ResultedInInvoice",
    sourceEntity: "Visits",
    targetEntity: "Invoices",
    relationshipType: "Operational",
    cardinality: "1:0..1 (optional)",
    direction: "Visits -> Invoices",
    strength: "Weak",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: false, description: "Indirect only, via VisitDate/InvoiceDate proximity." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Visits.InvoiceNo (nullable)", allowedNavigationTypes: ["Direct"], reverseAllowed: false, path: null, aggregationSources: null },
    queryExamples: ["Did this visit result in an invoice, and for how much?"],
    businessRuleConsumers: ["Strike Rate (productive visit = resulted in an invoice)"],
    engineConsumers: ["SGI", "Route Intelligence"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "RT",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-RT-005",
    name: "Route_HasVanLoads",
    sourceEntity: "Routes",
    targetEntity: "Van Loads",
    relationshipType: "Operational",
    cardinality: "1:N",
    direction: "Routes -> Van Loads",
    strength: "Strong",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: true, description: "LoadDate anchors this relationship." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Van Loads.RouteID", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["All loads onto Route X this week."],
    businessRuleConsumers: ["Van Reconciliation Rule"],
    engineConsumers: ["Route Intelligence", "Executive Studio"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "RT",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-RT-006",
    name: "Product_LoadedInVanLoads",
    sourceEntity: "Products",
    targetEntity: "Van Loads",
    relationshipType: "Reference",
    cardinality: "1:N",
    direction: "Products -> Van Loads",
    strength: "Strong",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: false, description: "Indirect, via LoadDate." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Van Loads.ProductCode", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["How much of Product X was loaded across all routes this month?"],
    businessRuleConsumers: ["Van Reconciliation Rule"],
    engineConsumers: ["Demand Intelligence", "Route Intelligence"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "RT",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-RT-007",
    name: "Route_HasVanInventory",
    sourceEntity: "Routes",
    targetEntity: "Van Inventory",
    relationshipType: "Snapshot",
    cardinality: "1:N",
    direction: "Routes -> Van Inventory",
    strength: "Strong",
    lifecycle: "Active (each row is a fixed-date snapshot)",
    timeAwareness: { isTimeAware: true, description: "ReportDate anchors this relationship." },
    snapshotBehavior: { isSnapshot: true, description: "Each row is a physically-measured balance at a specific ReportDate — never retroactively updated." },
    navigation: { foreignKey: "Van Inventory.RouteID", allowedNavigationTypes: ["Direct", "Context", "Snapshot"], reverseAllowed: false, path: null, aggregationSources: null },
    queryExamples: ["What was the last reported inventory balance on Route X?"],
    businessRuleConsumers: ["Van Reconciliation Rule"],
    engineConsumers: ["Route Intelligence", "Executive Studio"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "RT",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-RT-008",
    name: "Product_InVanInventory",
    sourceEntity: "Products",
    targetEntity: "Van Inventory",
    relationshipType: "Reference",
    cardinality: "1:N",
    direction: "Products -> Van Inventory",
    strength: "Strong",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: false, description: "Indirect, via ReportDate." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Van Inventory.ProductCode", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["Which routes currently carry stock of Product X?"],
    businessRuleConsumers: ["Van Reconciliation Rule"],
    engineConsumers: ["Route Intelligence"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "RT",
    sourceOfTruth: SOT,
  },

  // ===================== CU =====================
  {
    relationshipId: "REL-CU-001",
    name: "Customer_HasInvoices",
    sourceEntity: "Customers",
    targetEntity: "Invoices",
    relationshipType: "Operational",
    cardinality: "1:N",
    direction: "Customers -> Invoices",
    strength: "Strong",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: true, description: "InvoiceDate anchors this relationship." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Invoices.CustomerCode", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["All invoices for Customer X in the last quarter."],
    businessRuleConsumers: ["Lost Sales", "Customer Health", "Customer Priority"],
    engineConsumers: ["Customer 360", "Demand Intelligence", "SGI"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CU",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-CU-002",
    name: "Route_SnapshotOnInvoices",
    sourceEntity: "Routes",
    targetEntity: "Invoices",
    relationshipType: "Snapshot",
    cardinality: "1:N",
    direction: "Routes -> Invoices",
    strength: "Strong",
    lifecycle: "Active (fixed after issuance)",
    timeAwareness: { isTimeAware: true, description: "InvoiceDate anchors this relationship." },
    snapshotBehavior: {
      isSnapshot: true,
      description: "Invoices.RouteID is the route as it actually was at invoicing time — documented Intentional Denormalization in the Canonical Database, never resolved via Route Assignment.",
    },
    navigation: { foreignKey: "Invoices.RouteID", allowedNavigationTypes: ["Direct", "Context", "Snapshot"], reverseAllowed: false, path: null, aggregationSources: null },
    queryExamples: ["Total sales that actually occurred on Route X in January, regardless of who manages it now."],
    businessRuleConsumers: [],
    engineConsumers: ["Route Intelligence", "Executive Studio"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CU",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-CU-003",
    name: "Invoice_HasItems",
    sourceEntity: "Invoices",
    targetEntity: "Invoice Items",
    relationshipType: "Operational",
    cardinality: "1:N",
    direction: "Invoices -> Invoice Items",
    strength: "Strong",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: true, description: "Inherited from Invoice.InvoiceDate." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Invoice Items.InvoiceNo", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["All line items on Invoice X."],
    businessRuleConsumers: ["Cross Sell", "Product Opportunity"],
    engineConsumers: ["Customer 360", "Demand Intelligence"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CU",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-CU-004",
    name: "Product_SoldInInvoiceItems",
    sourceEntity: "Products",
    targetEntity: "Invoice Items",
    relationshipType: "Reference",
    cardinality: "1:N",
    direction: "Products -> Invoice Items",
    strength: "Strong",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: false, description: "Indirect, via Invoice.InvoiceDate." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Invoice Items.ProductCode", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["All sales of Product X in the last month."],
    businessRuleConsumers: ["Cross Sell", "SKU Expansion", "Lost Sales"],
    engineConsumers: ["Demand Intelligence", "SGI"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CU",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-CU-005",
    name: "Route_SnapshotOnInvoiceItems",
    sourceEntity: "Routes",
    targetEntity: "Invoice Items",
    relationshipType: "Snapshot",
    cardinality: "1:N",
    direction: "Routes -> Invoice Items",
    strength: "Strong",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: true, description: "Inherited from Invoice Items.RouteID." },
    snapshotBehavior: { isSnapshot: true, description: "Same Intentional Denormalization principle as REL-CU-002, at line-item level." },
    navigation: { foreignKey: "Invoice Items.RouteID", allowedNavigationTypes: ["Direct", "Context", "Snapshot"], reverseAllowed: false, path: null, aggregationSources: null },
    queryExamples: ["Distribution of Product X sales by route, as it actually happened."],
    businessRuleConsumers: [],
    engineConsumers: ["Demand Intelligence"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CU",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-CU-006",
    name: "Customer_HasReturns",
    sourceEntity: "Customers",
    targetEntity: "Returns",
    relationshipType: "Operational",
    cardinality: "1:N",
    direction: "Customers -> Returns",
    strength: "Strong",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: true, description: "ReturnDate anchors this relationship." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Returns.CustomerCode", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["All returns from Customer X."],
    businessRuleConsumers: ["Customer Health"],
    engineConsumers: ["Customer 360"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CU",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-CU-007",
    name: "Route_SnapshotOnReturns",
    sourceEntity: "Routes",
    targetEntity: "Returns",
    relationshipType: "Snapshot",
    cardinality: "1:N",
    direction: "Routes -> Returns",
    strength: "Strong",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: true, description: "ReturnDate anchors this relationship." },
    snapshotBehavior: { isSnapshot: true, description: "Returns.RouteID is a snapshot at return time." },
    navigation: { foreignKey: "Returns.RouteID", allowedNavigationTypes: ["Direct", "Context", "Snapshot"], reverseAllowed: false, path: null, aggregationSources: null },
    queryExamples: ["Total returns on Route X this month."],
    businessRuleConsumers: ["Van Reconciliation Rule"],
    engineConsumers: ["Route Intelligence"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CU",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-CU-008",
    name: "Invoice_HasReturns",
    sourceEntity: "Invoices",
    targetEntity: "Returns",
    relationshipType: "Operational",
    cardinality: "1:N (optional)",
    direction: "Invoices -> Returns",
    strength: "Weak",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: false, description: "Indirect." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Returns.InvoiceNo (nullable)", allowedNavigationTypes: ["Direct"], reverseAllowed: false, path: null, aggregationSources: null },
    queryExamples: ["Was any merchandise returned from Invoice X?"],
    businessRuleConsumers: [],
    engineConsumers: ["Customer 360"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CU",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-CU-009",
    name: "Return_HasItems",
    sourceEntity: "Returns",
    targetEntity: "Return Items",
    relationshipType: "Operational",
    cardinality: "1:N",
    direction: "Returns -> Return Items",
    strength: "Strong",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: true, description: "Inherited from Return.ReturnDate." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Return Items.ReturnNo", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["All line items on Return X and each item's reason."],
    businessRuleConsumers: [],
    engineConsumers: ["Customer 360"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CU",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-CU-010",
    name: "Product_ReturnedInItems",
    sourceEntity: "Products",
    targetEntity: "Return Items",
    relationshipType: "Reference",
    cardinality: "1:N",
    direction: "Products -> Return Items",
    strength: "Strong",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: false, description: "Indirect." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Return Items.ProductCode", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["Most-returned products this quarter and their reasons."],
    businessRuleConsumers: ["Van Reconciliation Rule"],
    engineConsumers: ["Demand Intelligence", "Route Intelligence"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CU",
    sourceOfTruth: SOT,
  },

  // ===================== FI =====================
  {
    relationshipId: "REL-FI-001",
    name: "Customer_HasCollections",
    sourceEntity: "Customers",
    targetEntity: "Collections",
    relationshipType: "Operational",
    cardinality: "1:N",
    direction: "Customers -> Collections",
    strength: "Strong",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: true, description: "CollectionDate anchors this relationship." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: { foreignKey: "Collections.CustomerCode", allowedNavigationTypes: ["Direct", "Reverse"], reverseAllowed: true, path: null, aggregationSources: null },
    queryExamples: ["All collections from Customer X."],
    businessRuleConsumers: ["Collection Risk", "Payment Priority", "Overdue Analysis"],
    engineConsumers: ["Customer 360", "Executive Studio"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "FI",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-FI-002",
    name: "Route_SnapshotOnCollections",
    sourceEntity: "Routes",
    targetEntity: "Collections",
    relationshipType: "Snapshot",
    cardinality: "1:N",
    direction: "Routes -> Collections",
    strength: "Strong",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: true, description: "CollectionDate anchors this relationship." },
    snapshotBehavior: { isSnapshot: true, description: "Collections.RouteID is a snapshot at collection time." },
    navigation: { foreignKey: "Collections.RouteID", allowedNavigationTypes: ["Direct", "Context", "Snapshot"], reverseAllowed: false, path: null, aggregationSources: null },
    queryExamples: ["Total collections on Route X this week."],
    businessRuleConsumers: ["Collection Risk"],
    engineConsumers: ["Route Intelligence"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "FI",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-FI-003",
    name: "Invoice_HasCollections",
    sourceEntity: "Invoices",
    targetEntity: "Collections",
    relationshipType: "Operational",
    cardinality: "1:N (optional)",
    direction: "Invoices -> Collections",
    strength: "Weak",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: false, description: "Indirect." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: {
      foreignKey: "Collections.InvoiceNo (nullable — empty = on-account payment)",
      allowedNavigationTypes: ["Direct"],
      reverseAllowed: false,
      path: null,
      aggregationSources: null,
    },
    queryExamples: ["Has Invoice X been fully paid?", "All on-account collections for Customer X."],
    businessRuleConsumers: ["Collection Risk", "Overdue Analysis"],
    engineConsumers: ["Customer 360", "Executive Studio"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "FI",
    sourceOfTruth: SOT,
  },

  // ===================== PR =====================
  {
    relationshipId: "REL-PR-001",
    name: "Product_HasPrices",
    sourceEntity: "Products",
    targetEntity: "Price List",
    relationshipType: "Reference",
    cardinality: "1:N",
    direction: "Products -> Price List",
    strength: "Strong",
    lifecycle: "Active / Historical (via StartDate/EndDate)",
    timeAwareness: { isTimeAware: true, description: "Date-Effective Pricing — genuinely temporal, not a fixed Snapshot." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: {
      foreignKey: "Price List.ProductCode",
      allowedNavigationTypes: ["Direct", "Context", "Temporal"],
      reverseAllowed: true,
      path: null,
      aggregationSources: null,
    },
    queryExamples: ["What was the price of Product X on 2026-05-01?"],
    businessRuleConsumers: [],
    engineConsumers: ["Demand Intelligence", "SGI"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "PR",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-PR-002",
    name: "Customer_HasDefaultPriceList",
    sourceEntity: "Customers",
    targetEntity: "Price List",
    relationshipType: "Reference",
    cardinality: "N:1",
    direction: "Customers -> Price List",
    strength: "Weak",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: false, description: "Indirect — composed with Price List's own temporal effectivity at actual pricing time." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: {
      foreignKey: "Customers.DefaultPriceListCode",
      allowedNavigationTypes: ["Direct"],
      reverseAllowed: false,
      path: null,
      aggregationSources: null,
    },
    queryExamples: ["What is Customer X's default price list?"],
    businessRuleConsumers: [],
    engineConsumers: ["Demand Intelligence", "Customer 360"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "PR",
    sourceOfTruth: SOT,
  },

  // ===================== PL =====================
  {
    relationshipId: "REL-PL-001",
    name: "Route_HasTargets",
    sourceEntity: "Routes",
    targetEntity: "Targets",
    relationshipType: "Temporal",
    cardinality: "1:1 per (Month, Year)",
    direction: "Routes -> Targets",
    strength: "Strong",
    lifecycle: "Active (period-scoped; not updated after the period ends)",
    timeAwareness: { isTimeAware: true, description: "Month/Year anchors this relationship." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: {
      foreignKey: "Targets.(Month,Year,RouteID) composite key",
      allowedNavigationTypes: ["Direct", "Context", "Temporal"],
      reverseAllowed: true,
      path: null,
      aggregationSources: null,
    },
    queryExamples: ["What is Route X's target for March 2026?"],
    businessRuleConsumers: ["Target Achievement"],
    engineConsumers: ["SGI", "Sales Team 360", "Executive Studio"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "PL",
    sourceOfTruth: SOT,
  },

  // ===================== CAL =====================
  {
    relationshipId: "REL-CAL-001",
    name: "Visit_OccursOn",
    sourceEntity: "Visits",
    targetEntity: "Sales Calendar",
    relationshipType: "Temporal",
    cardinality: "N:1",
    direction: "Visits -> Sales Calendar",
    strength: "Weak",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: true, description: "Direct — VisitDate = SalesCalendar.CalendarDate." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: {
      foreignKey: "Visits.VisitDate = Sales Calendar.CalendarDate (logical join, not a stored FK)",
      allowedNavigationTypes: ["Direct", "Temporal"],
      reverseAllowed: false,
      path: null,
      aggregationSources: null,
    },
    queryExamples: ["Did this visit occur on a working day or a holiday?"],
    businessRuleConsumers: ["Visit Priority", "Coverage Analysis"],
    engineConsumers: ["SGI", "Route Intelligence"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CAL",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-CAL-002",
    name: "Invoice_OccursOn",
    sourceEntity: "Invoices",
    targetEntity: "Sales Calendar",
    relationshipType: "Temporal",
    cardinality: "N:1",
    direction: "Invoices -> Sales Calendar",
    strength: "Weak",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: true, description: "Direct — InvoiceDate = CalendarDate." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: {
      foreignKey: "Invoices.InvoiceDate = Sales Calendar.CalendarDate (logical join)",
      allowedNavigationTypes: ["Direct", "Temporal"],
      reverseAllowed: false,
      path: null,
      aggregationSources: null,
    },
    queryExamples: ["Ramadan sales versus the monthly average (via the Ramadan flag)."],
    businessRuleConsumers: ["Lost Sales", "Product Opportunity"],
    engineConsumers: ["SGI", "Demand Intelligence", "Executive Studio"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CAL",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-CAL-003",
    name: "Collection_OccursOn",
    sourceEntity: "Collections",
    targetEntity: "Sales Calendar",
    relationshipType: "Temporal",
    cardinality: "N:1",
    direction: "Collections -> Sales Calendar",
    strength: "Weak",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: true, description: "Direct — CollectionDate = CalendarDate." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: {
      foreignKey: "Collections.CollectionDate = Sales Calendar.CalendarDate (logical join)",
      allowedNavigationTypes: ["Direct", "Temporal"],
      reverseAllowed: false,
      path: null,
      aggregationSources: null,
    },
    queryExamples: ["Actual collections versus working days in the month."],
    businessRuleConsumers: ["Collection Risk"],
    engineConsumers: ["Executive Studio"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CAL",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-CAL-004",
    name: "Return_OccursOn",
    sourceEntity: "Returns",
    targetEntity: "Sales Calendar",
    relationshipType: "Temporal",
    cardinality: "N:1",
    direction: "Returns -> Sales Calendar",
    strength: "Weak",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: true, description: "Direct — ReturnDate = CalendarDate." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: {
      foreignKey: "Returns.ReturnDate = Sales Calendar.CalendarDate (logical join)",
      allowedNavigationTypes: ["Direct", "Temporal"],
      reverseAllowed: false,
      path: null,
      aggregationSources: null,
    },
    queryExamples: ["Do return rates rise during PromotionSeason?"],
    businessRuleConsumers: [],
    engineConsumers: ["Demand Intelligence"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CAL",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-CAL-005",
    name: "VanLoad_OccursOn",
    sourceEntity: "Van Loads",
    targetEntity: "Sales Calendar",
    relationshipType: "Temporal",
    cardinality: "N:1",
    direction: "Van Loads -> Sales Calendar",
    strength: "Weak",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: true, description: "Direct — LoadDate = CalendarDate." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: {
      foreignKey: "Van Loads.LoadDate = Sales Calendar.CalendarDate (logical join)",
      allowedNavigationTypes: ["Direct", "Temporal"],
      reverseAllowed: false,
      path: null,
      aggregationSources: null,
    },
    queryExamples: ["Was this load performed on an official working day?"],
    businessRuleConsumers: ["Van Reconciliation Rule"],
    engineConsumers: ["Route Intelligence"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CAL",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-CAL-006",
    name: "RouteAssignment_PeriodBoundedBy",
    sourceEntity: "Route Assignments",
    targetEntity: "Sales Calendar",
    relationshipType: "Temporal",
    cardinality: "N:2 (StartDate and EndDate)",
    direction: "Route Assignments -> Sales Calendar",
    strength: "Weak",
    lifecycle: "Active",
    timeAwareness: { isTimeAware: true, description: "Direct — the period boundaries themselves." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: {
      foreignKey: "Route Assignments.(StartDate,EndDate) within Sales Calendar.CalendarDate range (logical join)",
      allowedNavigationTypes: ["Context", "Temporal"],
      reverseAllowed: false,
      path: null,
      aggregationSources: null,
    },
    queryExamples: ["How many actual working days did this assignment cover?"],
    businessRuleConsumers: [],
    engineConsumers: ["Sales Team 360"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CAL",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-CAL-007",
    name: "PriceList_EffectiveOn",
    sourceEntity: "Price List",
    targetEntity: "Sales Calendar",
    relationshipType: "Temporal",
    cardinality: "N:2 (StartDate and EndDate)",
    direction: "Price List -> Sales Calendar",
    strength: "Weak",
    lifecycle: "Active / Expired",
    timeAwareness: { isTimeAware: true, description: "Direct — the effectivity boundaries themselves." },
    snapshotBehavior: { isSnapshot: false, description: null },
    navigation: {
      foreignKey: "Price List.(StartDate,EndDate) within Sales Calendar.CalendarDate range (logical join)",
      allowedNavigationTypes: ["Context", "Temporal"],
      reverseAllowed: false,
      path: null,
      aggregationSources: null,
    },
    queryExamples: ["Which price lists are actually effective on date X?"],
    businessRuleConsumers: [],
    engineConsumers: ["Demand Intelligence"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "CAL",
    sourceOfTruth: SOT,
  },

  // ===================== DER =====================
  {
    relationshipId: "REL-DER-001",
    name: "Employee_EffectiveTarget",
    sourceEntity: "Employees",
    targetEntity: "Targets",
    relationshipType: "Multi-Hop",
    cardinality: "1:1 per (Month, Year), via path",
    direction: "Employees -> Targets",
    strength: "Derived",
    lifecycle: "Active (recomputed on every query, never persisted)",
    timeAwareness: { isTimeAware: true, description: "Route Assignment is evaluated as-of the requested Month/Year, not current state." },
    snapshotBehavior: { isSnapshot: false, description: "Each hop respects its own type (Route Assignment hop is Temporal)." },
    navigation: {
      foreignKey: null,
      allowedNavigationTypes: ["Multi-Hop"],
      reverseAllowed: false,
      path: [
        { relationshipId: "REL-ORG-008", traversalDirection: "forward" },
        { relationshipId: "REL-ORG-007", traversalDirection: "reverse" },
        { relationshipId: "REL-PL-001", traversalDirection: "forward" },
      ],
      aggregationSources: null,
    },
    queryExamples: ["What was Employee X's actual sales target during June 2026?"],
    businessRuleConsumers: ["Target Achievement"],
    engineConsumers: ["Sales Team 360", "Executive Studio", "Murshidak"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "DER",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-DER-002",
    name: "Visit_ConductedBy",
    sourceEntity: "Visits",
    targetEntity: "Employees",
    relationshipType: "Multi-Hop",
    cardinality: "N:1 via path",
    direction: "Visits -> Employees",
    strength: "Derived",
    lifecycle: "Active (recomputed on every query)",
    timeAwareness: { isTimeAware: true, description: "Route Assignment is evaluated as-of the exact VisitDate." },
    snapshotBehavior: {
      isSnapshot: false,
      description: "Visit.RouteID itself is a Snapshot (REL-RT-002); the second hop (Route Assignment) is a live temporal lookup as-of VisitDate.",
    },
    navigation: {
      foreignKey: null,
      allowedNavigationTypes: ["Multi-Hop"],
      reverseAllowed: false,
      path: [
        { relationshipId: "REL-RT-002", traversalDirection: "reverse" },
        { relationshipId: "REL-ORG-007", traversalDirection: "forward" },
        { relationshipId: "REL-ORG-008", traversalDirection: "reverse" },
      ],
      aggregationSources: null,
    },
    queryExamples: ["Which employee actually conducted this visit on 2025-11-02?"],
    businessRuleConsumers: ["Visit Priority"],
    engineConsumers: ["Sales Team 360", "SGI"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "DER",
    sourceOfTruth: SOT,
  },
  {
    relationshipId: "REL-DER-003",
    name: "VanLoad_ReconciledBalance",
    sourceEntity: "Van Loads",
    targetEntity: "Van Inventory",
    relationshipType: "Multi-Hop",
    cardinality: "N:N aggregated",
    direction: "Van Loads / Invoice Items / Return Items -> Van Inventory (comparison)",
    strength: "Derived",
    lifecycle: "Active (computed live, never persisted as an analytical table)",
    timeAwareness: { isTimeAware: true, description: "Computed within an explicit time window (e.g. one operational day or week)." },
    snapshotBehavior: {
      isSnapshot: false,
      description: "Van Inventory itself is a Snapshot (REL-RT-007); the derived balance = Sum(VanLoads.Quantity) - Sum(InvoiceItems.Quantity) - Sum(ReturnItems.Quantity) for the same Route+Product+Unit, compared against the measured Van Inventory snapshot.",
    },
    navigation: {
      foreignKey: null,
      allowedNavigationTypes: ["Multi-Hop"],
      reverseAllowed: false,
      path: null,
      aggregationSources: ["REL-RT-005", "REL-CU-005", "REL-CU-009", "REL-RT-007"],
    },
    queryExamples: ["Is there a shortage or surplus in Route X's van custody today?"],
    businessRuleConsumers: ["Van Reconciliation Rule"],
    engineConsumers: ["Route Intelligence", "Executive Studio", "Murshidak"],
    status: "Active",
    deprecatedBy: null,
    version: "1.0.0",
    domain: "DER",
    sourceOfTruth: SOT,
  },
] as const;
