import { Injectable } from "@nestjs/common";
import type { AuthenticatedUser } from "../../common/types/authenticated-user";
import { PrismaService } from "../../common/prisma";
import { RieFacade } from "../rie/rie-facade.service";
import type { RieScalableQuery, RieScalableQueryResult } from "../rie/scalable-query.types";

const TARGETS = [["SalesTarget", "هدف المبيعات", "sales", true, "currency"], ["CollectionTarget", "هدف التحصيل", "collections", true, "currency"], ["WeightTarget", "هدف الوزن", "weight", false, "weight"], ["ActiveCustomersTarget", "هدف العملاء النشطين", "customers", false, "count"], ["ProductiveCallsTarget", "هدف الزيارات المنتجة", "productiveCalls", false, "count"], ["SKUDistributionTarget", "هدف توزيع الأصناف", "skus", false, "count"]] as const;
type DashboardBenchmark = "previous-month" | "previous-quarter-average";
type Row = Record<string, unknown>;
const number = (v: unknown) => typeof v === "bigint" ? Number(v) : typeof v === "number" ? (Number.isFinite(v) ? v : null) : typeof v === "string" && v.trim() && Number.isFinite(Number(v.replace(/,/g, ""))) ? Number(v.replace(/,/g, "")) : null;
const key = (v: unknown) => String(v ?? "").slice(0, 10);
const monthStart = (d: Date, delta = 0) => new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + delta, 1));

@Injectable()
export class DashboardPerformanceService {
  constructor(private readonly rie: RieFacade, private readonly prisma: PrismaService) {}
  private ctx(user: AuthenticatedUser) { return { companyId: user.companyId!, requestingUser: { roleCode: user.roleCode, email: user.email } }; }
  private aggregate(query: RieScalableQuery): Promise<RieScalableQueryResult> { return this.rie.queryCanonicalRecords({ ...query, pagination: { limit: 500 } }); }

  async get(user: AuthenticatedUser, benchmark: DashboardBenchmark, routeIds?: string[], dateFrom?: string, dateTo?: string, comparisonFrom?: string, comparisonTo?: string) {
    const now = new Date(), currentFrom = dateFrom ? new Date(`${dateFrom}T00:00:00Z`) : monthStart(now), currentTo = dateTo ? new Date(`${dateTo}T23:59:59Z`) : now, comparisonStart = comparisonFrom ? new Date(`${comparisonFrom}T00:00:00Z`) : null, comparisonEnd = comparisonTo ? new Date(`${comparisonTo}T23:59:59Z`) : null, start = monthStart(currentFrom), next = monthStart(currentTo, 1), ctx = this.ctx(user), factFrom = (comparisonStart ?? monthStart(currentFrom, -3)).getTime(), factTo = currentTo.getTime();
    const routeScope = routeIds?.length ? { route: { values: routeIds } } : {};
    // Scope -> Join -> Aggregate: this service receives only daily KPI buckets,
    // never fact pages or raw rows to join/aggregate in Node.
    const [calendar, sales, collections, returns, visits, products, targets] = await Promise.all([
      this.prisma.salesCalendar.findMany({ where: { companyId: user.companyId!, calendarDate: { gte: start, lt: next }, workingDay: true }, orderBy: { calendarDate: "asc" } }),
      this.aggregate({ ...ctx, entityName: "Invoice Items", projection: [{ field: "InvoiceDate", source: "invoice", as: "date" }], groupBy: [{ field: "InvoiceDate", source: "invoice" }], joins: [{ entityName: "Invoices", alias: "invoice", on: { left: { field: "InvoiceNo" }, rightField: "InvoiceNo" } }, { entityName: "Products", alias: "product", type: "left", on: { left: { field: "ProductCode" }, rightField: "ProductCode" } }], hierarchyRoute: { field: "RouteID", source: "invoice" }, scope: { date: { field: "InvoiceDate", source: "invoice", from: factFrom, to: factTo }, ...(routeIds?.length ? { route: { values: routeIds, source: "invoice" } } : {}) }, aggregates: [{ op: "sum", field: "LineTotal", as: "sales" }, { op: "countDistinct", field: "InvoiceNo", as: "invoices" }, { op: "countDistinct", field: "CustomerCode", source: "invoice", as: "customers" }, { op: "countDistinct", field: "ProductCode", as: "skus" }, { op: "sumProduct", field: "Quantity", multiplier: { field: "Weight", source: "product" }, multiplierFallback: { field: "UnitWeight", source: "product" }, as: "weight" }] }),
      this.aggregate({ ...ctx, entityName: "Collections", projection: [{ field: "CollectionDate", as: "date" }], groupBy: [{ field: "CollectionDate" }], scope: { date: { field: "CollectionDate", from: factFrom, to: factTo }, ...routeScope }, aggregates: [{ op: "sum", field: "Amount", as: "collections" }] }),
      this.aggregate({ ...ctx, entityName: "Returns", projection: [{ field: "ReturnDate", as: "date" }], groupBy: [{ field: "ReturnDate" }], scope: { date: { field: "ReturnDate", from: factFrom, to: factTo }, ...routeScope }, aggregates: [{ op: "sum", field: "TotalAmount", as: "returns" }] }),
      this.aggregate({ ...ctx, entityName: "Visits", projection: [{ field: "VisitDate", as: "date" }, { field: "Status", as: "status" }, { field: "VisitStatus", as: "visitStatus" }], groupBy: [{ field: "VisitDate" }, { field: "Status" }, { field: "VisitStatus" }], scope: { date: { field: "VisitDate", from: factFrom, to: factTo }, ...routeScope }, aggregates: [{ op: "count", as: "calls" }] }),
      this.aggregate({ companyId: ctx.companyId, entityName: "Products", projection: [], aggregates: [{ op: "count", as: "products" }] }),
      this.aggregate({ ...ctx, entityName: "Targets", projection: [], scope: { ...routeScope, fields: [{ field: "Year", values: [String(currentTo.getUTCFullYear())] }, { field: "Month", values: [String(currentTo.getUTCMonth() + 1)] }] }, aggregates: TARGETS.map(([field]) => ({ op: "sum" as const, field, as: field })) }),
    ]);
    const selling = calendar.map((d) => d.calendarDate.getTime()).filter((d) => d >= currentFrom.getTime() && d <= currentTo.getTime()), elapsed = selling.length, total = calendar.length, warnings: string[] = []; if (!total) warnings.push("لا توجد أيام بيع مفعّلة للشهر الحالي في تقويم المبيعات.");
    const currentDates = new Set(selling.map((d) => key(new Date(d).toISOString()))), priorMonthDates = await this.firstSellingDates(user.companyId!, monthStart(currentFrom, -1), elapsed);
    const customMonths = comparisonStart && comparisonEnd ? await Promise.all(Array.from({ length: (comparisonEnd.getUTCFullYear() - comparisonStart.getUTCFullYear()) * 12 + comparisonEnd.getUTCMonth() - comparisonStart.getUTCMonth() + 1 }, (_, i) => this.firstSellingDates(user.companyId!, new Date(Date.UTC(comparisonStart.getUTCFullYear(), comparisonStart.getUTCMonth() + i, 1)), elapsed))) : null;
    const benchmarkDates = customMonths?.length ? customMonths : benchmark === "previous-quarter-average" ? await this.previousQuarterDates(user.companyId!, currentFrom, elapsed) : [priorMonthDates];
    const byDate = (result: RieScalableQueryResult) => new Map(result.records.map((r) => [key(r.date), r as Row])); const saleByDate = byDate(sales), collectionByDate = byDate(collections), returnByDate = byDate(returns), callsByDate = new Map<string, number>();
    for (const row of visits.records as Row[]) { const status = String(row.status ?? row.visitStatus ?? "").toLowerCase(); if (status === "productive" || status === "منتجة") { const date = key(row.date); callsByDate.set(date, (callsByDate.get(date) ?? 0) + (number(row.calls) ?? 0)); } }
    type Acc = { sales: number; invoices: number; customers: number; skus: number; weight: number; collections: number; returns: number; productiveCalls: number; daily: Record<string, Map<string, number>> };
    const calculate = (dateSet: Set<string>): Acc => { const a: Acc = { sales: 0, invoices: 0, customers: 0, skus: 0, weight: 0, collections: 0, returns: 0, productiveCalls: 0, daily: { sales: new Map(), invoices: new Map(), customers: new Map(), skus: new Map(), collections: new Map(), returns: new Map() } }; for (const date of dateSet) { const sale = saleByDate.get(date), collection = collectionByDate.get(date), returned = returnByDate.get(date); for (const [metric, row, field] of [["sales", sale, "sales"], ["invoices", sale, "invoices"], ["customers", sale, "customers"], ["skus", sale, "skus"], ["collections", collection, "collections"], ["returns", returned, "returns"]] as const) { const value = number(row?.[field]) ?? 0; a[metric] = (a[metric] ?? 0) + value; a.daily[metric]?.set(date, value); } a.weight += number(sale?.weight) ?? 0; a.productiveCalls += callsByDate.get(date) ?? 0; } return a; };
    const cur = calculate(currentDates), comparisons = benchmarkDates.map(calculate);
    // Daily buckets retain the old sparkline formula. Distinct KPI totals
    // must be calculated across each whole selling-day set (not summed from
    // per-day distinct buckets), exactly like the former Set-based logic.
    const distinctFor = (dateSet: Set<string>) => dateSet.size ? this.aggregate({ ...ctx, entityName: "Invoice Items", projection: [], joins: [{ entityName: "Invoices", alias: "invoice", on: { left: { field: "InvoiceNo" }, rightField: "InvoiceNo" } }], hierarchyRoute: { field: "RouteID", source: "invoice" }, scope: { date: { field: "InvoiceDate", source: "invoice", values: Array.from(dateSet) }, ...(routeIds?.length ? { route: { values: routeIds, source: "invoice" } } : {}) }, aggregates: [{ op: "countDistinct", field: "InvoiceNo", as: "invoices" }, { op: "countDistinct", field: "CustomerCode", source: "invoice", as: "customers" }, { op: "countDistinct", field: "ProductCode", as: "skus" }] }) : Promise.resolve(null);
    const distincts = await Promise.all([distinctFor(currentDates), ...benchmarkDates.map(distinctFor)]);
    const applyDistinct = (acc: Acc, result: RieScalableQueryResult | null) => { const row = result?.records[0] as Row | undefined; acc.invoices = number(row?.invoices) ?? 0; acc.customers = number(row?.customers) ?? 0; acc.skus = number(row?.skus) ?? 0; };
    applyDistinct(cur, distincts[0] ?? null); comparisons.forEach((acc, index) => applyDistinct(acc, distincts[index + 1] ?? null));
    const avg = (get: (a: Acc) => number) => comparisons.length ? comparisons.reduce((sum, a) => sum + get(a), 0) / comparisons.length : null, spark = (metric: keyof Acc["daily"]) => selling.map((d) => cur.daily[metric]?.get(key(new Date(d).toISOString())) ?? 0), metric = (current: number | null, previous: number | null, values: number[]) => ({ current, benchmark: previous, growthPct: current !== null && previous !== null && previous !== 0 ? ((current - previous) / previous) * 100 : null, sparkline: values });
    const hasProducts = (number(products.records[0]?.products) ?? 0) > 0, actual: Record<string, number | null> = { sales: cur.sales, collections: cur.collections, weight: hasProducts ? cur.weight : null, customers: cur.customers, productiveCalls: cur.productiveCalls, skus: cur.skus }, target = targets.records[0] as Row | undefined;
    const targetCards = TARGETS.map(([field, label, actualKey, primary, unit]) => { const monthlyTarget = number(target?.[field]) ?? 0; if (!monthlyTarget) return null; const value = actual[actualKey] ?? null, targetMtd = total ? monthlyTarget * elapsed / total : 0, remaining = value === null ? null : Math.max(monthlyTarget - value, 0); return { key: field, label, monthlyTarget, actualMtd: value, targetMtd, aheadBehind: value === null ? null : value - targetMtd, progressPct: value === null || !targetMtd ? null : value / targetMtd * 100, remainingMonthlyTarget: remaining, requiredDailyVelocity: remaining === null || total - elapsed <= 0 ? null : remaining / (total - elapsed), runRateForecast: value === null || !elapsed ? null : value / elapsed * total, primary, unit }; }).filter((v): v is NonNullable<typeof v> => v !== null);
    const priority = ["SalesTarget", "CollectionTarget", "ProductiveCallsTarget", "ActiveCustomersTarget", "SKUDistributionTarget", "WeightTarget"], hasHigherSecondary = targetCards.some((x) => !x.primary && x.key !== "WeightTarget"), orderedTargets = targetCards.filter((x) => x.key !== "WeightTarget" || !hasHigherSecondary).sort((a, b) => priority.indexOf(a.key) - priority.indexOf(b.key));
    return { periodMonth: key(start).slice(0, 7), benchmark, sellingDays: { elapsed, total, remaining: Math.max(total - elapsed, 0), available: total > 0 }, metrics: { sales: metric(cur.sales, avg((a) => a.sales), spark("sales")), collections: metric(cur.collections, avg((a) => a.collections), spark("collections")), invoices: metric(cur.invoices, avg((a) => a.invoices), spark("invoices")), customers: metric(cur.customers, avg((a) => a.customers), spark("customers")), skus: metric(cur.skus, avg((a) => a.skus), spark("skus")), returns: metric(cur.returns, avg((a) => a.returns), spark("returns")) }, targets: orderedTargets, warnings };
  }
  private async firstSellingDates(companyId: string, start: Date, count: number) { const days = await this.prisma.salesCalendar.findMany({ where: { companyId, calendarDate: { gte: start, lt: monthStart(start, 1) }, workingDay: true }, orderBy: { calendarDate: "asc" } }); return new Set(days.slice(0, count).map((d) => d.calendarDate.toISOString().slice(0, 10))); }
  private previousQuarterDates(companyId: string, now: Date, count: number) { return Promise.all([1, 2, 3].map((i) => this.firstSellingDates(companyId, monthStart(now, -i), count))); }
}
