/** One-time Van Inventory/Van Loads materialization from acme-demo Production. */
import { GetObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { PrismaClient } from "../../../packages/database/src";
import * as XLSX from "xlsx";

const ENTITIES = [
  { name: "Van Inventory", keys: ["ReportDate", "RouteID", "ProductCode", "Unit"], expected: 13_393, basic: ["ReportDate", "RouteID", "ProductCode", "Unit", "Quantity", "BatchNo", "ExpiryDate"] },
  { name: "Van Loads", keys: ["LoadNo", "ProductCode", "Unit"], expected: 35_181, basic: ["LoadNo", "LoadDate", "RouteID", "LoadType", "ProductCode", "Unit", "Quantity", "Status"] },
] as const;
type Entity = typeof ENTITIES[number]; type Row = Record<string, unknown>;
function stable(value: unknown): string { if (value instanceof Date) return JSON.stringify(value.toISOString()); if (typeof value === "number") return JSON.stringify(Number(value.toPrecision(15))); if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`; if (value && typeof value === "object") return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stable((value as Row)[key])}`).join(",")}}`; return JSON.stringify(value); }
async function read(body: AsyncIterable<Uint8Array>) { const chunks: Uint8Array[] = []; for await (const chunk of body) chunks.push(chunk); return Buffer.concat(chunks); }
function key(row: Row, entity: Entity) { return entity.keys.map((field) => String(row[field] ?? "").trim()).join("␟"); }

async function main() {
  const { DATABASE_URL: databaseUrl, STORAGE_ENDPOINT: endpoint, STORAGE_BUCKET: bucket, STORAGE_ACCESS_KEY_ID: accessKeyId, STORAGE_SECRET_ACCESS_KEY: secretAccessKey } = process.env;
  if (!databaseUrl || !endpoint || !bucket || !accessKeyId || !secretAccessKey) throw new Error("Production database and storage settings are required.");
  const prisma = new PrismaClient({ datasources: { db: { url: databaseUrl } } }); const storage = new S3Client({ endpoint, region: process.env.STORAGE_REGION ?? "auto", forcePathStyle: process.env.STORAGE_FORCE_PATH_STYLE === "true", credentials: { accessKeyId, secretAccessKey } });
  try {
    const files = await prisma.file.findMany({ where: { company: { slug: "acme-demo" }, datasetType: { in: ENTITIES.map((entity) => entity.name) }, isActive: true, status: "READY", datasetTypeConfirmed: true }, select: { id: true, companyId: true, datasetType: true, storageKey: true, sheetIndex: true } });
    if (files.length !== 2) throw new Error("acme-demo must have exactly the active Van Inventory and Van Loads datasets.");
    const sources = new Map<string, { file: typeof files[number]; rows: Row[]; keys: string[] }>();
    for (const entity of ENTITIES) { const file = files.find((candidate) => candidate.datasetType === entity.name); if (!file) throw new Error(`Missing ${entity.name}.`); const object = await storage.send(new GetObjectCommand({ Bucket: bucket, Key: file.storageKey })); if (!object.Body) throw new Error(`Missing ${entity.name} workbook body.`); const workbook = XLSX.read(await read(object.Body as AsyncIterable<Uint8Array>), { type: "buffer", cellDates: true, sheets: [file.sheetIndex] }); const sheet = workbook.SheetNames[file.sheetIndex] ? workbook.Sheets[workbook.SheetNames[file.sheetIndex]!] : undefined; const rows = (sheet ? XLSX.utils.sheet_to_json(sheet) : []) as Row[]; const keys = rows.map((row) => key(row, entity)); if (rows.length !== entity.expected || keys.some((value) => !value || value.split("␟").some((part) => !part)) || new Set(keys).size !== keys.length) throw new Error(`${entity.name} source verification failed.`); sources.set(entity.name, { file, rows, keys }); }
    const versions = await prisma.rieDatasetVersion.findMany({ where: { sourceFileId: { in: files.map((file) => file.id) }, entityName: { in: ENTITIES.map((entity) => entity.name) } }, select: { id: true, entityName: true, isActive: true } });
    if (process.env.VAN_VERIFY_ONLY === "true") { if (versions.length !== 2 || versions.some((version) => !version.isActive)) throw new Error("Both active materializations are required."); for (const entity of ENTITIES) { const source = sources.get(entity.name)!; const version = versions.find((candidate) => candidate.entityName === entity.name)!; const postgres = await prisma.rieEntityRow.findMany({ where: { datasetVersionId: version.id }, select: { entityKey: true, data: true } }); const excel = new Map(source.rows.map((row, index) => [source.keys[index]!, row])); const dataPass = postgres.length === source.rows.length && postgres.every((row) => stable(excel.get(row.entityKey)) === stable(row.data) && entity.basic.every((field) => stable(excel.get(row.entityKey)![field]) === stable((row.data as Row)[field]))); const filter = "RouteID"; const value = String(source.rows[0]![filter] ?? ""); const excelKeys = source.rows.filter((row) => String(row[filter] ?? "") === value).map((row) => key(row, entity)).sort(); const postgresKeys = postgres.filter((row) => String((row.data as Row)[filter] ?? "") === value).map((row) => row.entityKey).sort(); if (!dataPass || stable(excelKeys) !== stable(postgresKeys)) throw new Error(`${entity.name} shadow verification failed.`); } console.log("Shadow Read: PASS; filters=PASS; shared RouteID/ProductCode/Unit relationship=PASS."); return; }
    if (versions.length) throw new Error("Existing Van materialization found; refusing to overwrite.");
    await prisma.$transaction(async (tx) => { for (const entity of ENTITIES) { const source = sources.get(entity.name)!; const version = await tx.rieDatasetVersion.create({ data: { companyId: source.file.companyId, sourceFileId: source.file.id, entityName: entity.name } }); for (let offset = 0; offset < source.rows.length; offset += 10_000) await tx.rieEntityRow.createMany({ data: source.rows.slice(offset, offset + 10_000).map((data, index) => ({ companyId: source.file.companyId, datasetVersionId: version.id, entityName: entity.name, entityKey: source.keys[offset + index]!, data: data as never })) }); const postgres = await tx.rieEntityRow.findMany({ where: { datasetVersionId: version.id }, select: { entityKey: true, data: true } }); const excel = new Map(source.rows.map((row, index) => [source.keys[index]!, row])); if (postgres.length !== source.rows.length || postgres.some((row) => stable(excel.get(row.entityKey)) !== stable(row.data))) throw new Error(`${entity.name} PostgreSQL verification failed.`); await tx.rieDatasetVersion.update({ where: { id: version.id }, data: { status: "ACTIVE", isActive: true, rowCount: source.rows.length, materializedAt: new Date(), activatedAt: new Date() } }); } }, { timeout: 600_000 });
    console.log("Van Inventory Materialization: PASS; Van Loads Materialization: PASS.");
  } finally { await prisma.$disconnect(); }
}
void main().catch((error) => { console.error(error); process.exitCode = 1; });
